package com.candyacademia.spsslite;
import javax.swing.*;import javax.swing.table.DefaultTableModel;import java.awt.*;import java.util.*;import java.util.List;
public final class AdvancedChartPanel extends JPanel{
 public enum Mode{SCATTER,LINE,BAR,BOX}
 private final String title,xLabel,yLabel;private final double[]x,y;private final Mode mode;private final Map<String,Integer>categories;
 public AdvancedChartPanel(String title,String xLabel,String yLabel,double[]x,double[]y,Mode mode){this.title=title;this.xLabel=xLabel;this.yLabel=yLabel;this.x=x;this.y=y;this.mode=mode;this.categories=null;setPreferredSize(new Dimension(760,500));setBackground(AppTheme.BG);}
 public AdvancedChartPanel(String title,Map<String,Integer>categories){this.title=title;this.xLabel="Category";this.yLabel="Frequency";this.x=this.y=null;this.mode=Mode.BAR;this.categories=categories;setPreferredSize(new Dimension(760,500));setBackground(AppTheme.BG);}
 protected void paintComponent(Graphics g){super.paintComponent(g);Graphics2D q=(Graphics2D)g.create();q.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);int w=getWidth(),h=getHeight(),l=70,r=30,t=55,b=65;q.setColor(AppTheme.TEXT);q.setFont(new Font(Font.SANS_SERIF,Font.BOLD,19));q.drawString(title,l,30);q.setColor(AppTheme.BORDER);q.fillRoundRect(l,t,w-l-r,h-t-b,12,12);q.setColor(AppTheme.CARD);q.fillRect(l+1,t+1,w-l-r-2,h-t-b-2);q.setColor(AppTheme.TEXT);q.drawLine(l,h-b,w-r,h-b);q.drawLine(l,t,l,h-b);if(mode==Mode.BAR)bars(q,l,t,w-r,h-b);else if(mode==Mode.BOX)box(q,l,t,w-r,h-b);else series(q,l,t,w-r,h-b);q.setFont(new Font(Font.SANS_SERIF,Font.BOLD,12));q.drawString(xLabel,(w-q.getFontMetrics().stringWidth(xLabel))/2,h-18);q.rotate(-Math.PI/2);q.drawString(yLabel,-(h+q.getFontMetrics().stringWidth(yLabel))/2,20);q.dispose();}
 private void series(Graphics2D g,int l,int t,int rr,int bb){if(x==null||y==null||x.length==0)return;double xmin=Arrays.stream(x).min().orElse(0),xmax=Arrays.stream(x).max().orElse(1),ymin=Arrays.stream(y).min().orElse(0),ymax=Arrays.stream(y).max().orElse(1);if(xmax==xmin)xmax++;if(ymax==ymin)ymax++;g.setColor(AppTheme.BLUE);g.setStroke(new BasicStroke(2f));int px=0,py=0;for(int i=0;i<Math.min(x.length,y.length);i++){int xx=l+(int)((x[i]-xmin)/(xmax-xmin)*(rr-l)),yy=bb-(int)((y[i]-ymin)/(ymax-ymin)*(bb-t));if(mode==Mode.LINE&&i>0)g.drawLine(px,py,xx,yy);g.fillOval(xx-4,yy-4,8,8);px=xx;py=yy;}labels(g,l,t,rr,bb,xmin,xmax,ymin,ymax);}
 private void bars(Graphics2D g,int l,int t,int rr,int bb){if(categories==null||categories.isEmpty())return;int max=categories.values().stream().mapToInt(Integer::intValue).max().orElse(1),n=categories.size(),gap=12,bw=Math.max(8,(rr-l-gap*(n+1))/n),i=0;g.setFont(new Font(Font.SANS_SERIF,Font.PLAIN,11));for(var e:categories.entrySet()){int x=l+gap+i*(bw+gap),bh=(int)((double)e.getValue()/max*(bb-t-25));g.setColor(new Color(42,111,219));g.fillRoundRect(x,bb-bh,bw,bh,8,8);g.setColor(AppTheme.TEXT);String label=e.getKey().length()>12?e.getKey().substring(0,12):e.getKey();g.drawString(label,x,bb+18);g.drawString(String.valueOf(e.getValue()),x,bb-bh-5);i++;}}
 private void box(Graphics2D g,int l,int t,int rr,int bb){if(y==null||y.length<2)return;double[]a=y.clone();Arrays.sort(a);double min=a[0],q1=quantile(a,.25),med=quantile(a,.5),q3=quantile(a,.75),max=a[a.length-1];int cx=(l+rr)/2,bw=150;int ymin=bb-20,ymax=t+20;java.util.function.DoubleFunction<Integer>p=v->ymin-(int)((v-min)/(max-min==0?1:max-min)*(ymin-ymax));g.setColor(AppTheme.BLUE);g.setStroke(new BasicStroke(3));g.drawLine(cx,p.apply(min),cx,p.apply(max));g.fillRect(cx-35,p.apply(min)-2,70,4);g.fillRect(cx-35,p.apply(max)-2,70,4);g.setColor(new Color(105,155,235,120));g.fillRect(cx-bw/2,p.apply(q3),bw,p.apply(q1)-p.apply(q3));g.setColor(AppTheme.NAVY);g.drawRect(cx-bw/2,p.apply(q3),bw,p.apply(q1)-p.apply(q3));g.fillRect(cx-bw/2,p.apply(med)-2,bw,4);g.drawString(String.format("Min %.3f   Q1 %.3f   Median %.3f   Q3 %.3f   Max %.3f",min,q1,med,q3,max),l,bb+28);}
 private void labels(Graphics2D g,int l,int t,int rr,int bb,double xmin,double xmax,double ymin,double ymax){g.setColor(AppTheme.MUTED);g.setFont(new Font(Font.MONOSPACED,Font.PLAIN,10));g.drawString(String.format("%.2f",xmin),l,bb+16);g.drawString(String.format("%.2f",xmax),rr-35,bb+16);g.drawString(String.format("%.2f",ymin),l-45,bb);g.drawString(String.format("%.2f",ymax),l-45,t+5);}
 private static double quantile(double[]a,double p){double x=p*(a.length-1);int i=(int)x;return i==a.length-1?a[i]:a[i]+(x-i)*(a[i+1]-a[i]);}
 public static JPanel dashboard(DefaultTableModel model){JPanel root=new JPanel(new BorderLayout(12,12));root.setBorder(BorderFactory.createEmptyBorder(18,18,18,18));JLabel h=new JLabel("DATA EXPLORATION DASHBOARD — "+model.getRowCount()+" cases, "+model.getColumnCount()+" variables");h.setFont(new Font(Font.SANS_SERIF,Font.BOLD,18));root.add(h,BorderLayout.NORTH);JPanel grid=new JPanel(new GridLayout(1,2,12,12));List<Integer>nums=new ArrayList<>();for(int c=0;c<model.getColumnCount();c++)if(DataSet.numeric(model,c).size()>=2)nums.add(c);if(nums.size()>=2){double[]a=DataSet.numeric(model,nums.get(0)).stream().mapToDouble(Double::doubleValue).toArray(),b=DataSet.numeric(model,nums.get(1)).stream().mapToDouble(Double::doubleValue).toArray();int n=Math.min(a.length,b.length);grid.add(new AdvancedChartPanel("Relationship",model.getColumnName(nums.get(0)),model.getColumnName(nums.get(1)),Arrays.copyOf(a,n),Arrays.copyOf(b,n),Mode.SCATTER));grid.add(new AdvancedChartPanel("Distribution",model.getColumnName(nums.get(0)),"Value",new double[a.length],a,Mode.BOX));}else grid.add(new JLabel("Load numeric data to populate the visual dashboard.",SwingConstants.CENTER));root.add(grid);return root;}
}
