package com.candyacademia.spsslite;
import javax.swing.*;import javax.swing.border.EmptyBorder;import java.awt.*;
public final class AppTheme {
 public static final Color NAVY=new Color(5,10,20),NAVY_2=new Color(15,23,42),BLUE=new Color(37,99,235),CYAN=new Color(34,211,238),BG=new Color(8,15,29),CARD=new Color(15,23,42),SURFACE=new Color(24,35,55),TEXT=new Color(248,250,252),BODY=new Color(226,232,240),HEADING=new Color(103,232,249),INTERACTIVE=new Color(147,197,253),MUTED=new Color(174,190,211),BORDER=new Color(55,72,98),SUCCESS=new Color(52,211,153),WARNING=new Color(251,191,36);
 private AppTheme(){}
 public static void install(){Font buttonFont=new Font(Font.SANS_SERIF,Font.BOLD,14);UIManager.put("Panel.background",BG);UIManager.put("OptionPane.background",CARD);UIManager.put("OptionPane.messageForeground",BODY);UIManager.put("Label.foreground",BODY);UIManager.put("Button.font",buttonFont);UIManager.put("Button.foreground",TEXT);UIManager.put("Button.background",SURFACE);UIManager.put("Button.disabledText",new Color(120,137,161));UIManager.put("Button.focus",CYAN);UIManager.put("TextField.background",SURFACE);UIManager.put("TextField.foreground",BODY);UIManager.put("TextField.caretForeground",CYAN);UIManager.put("TextField.selectionBackground",BLUE);UIManager.put("TextField.selectionForeground",Color.WHITE);UIManager.put("PasswordField.background",SURFACE);UIManager.put("PasswordField.foreground",BODY);UIManager.put("PasswordField.caretForeground",CYAN);UIManager.put("TextArea.background",SURFACE);UIManager.put("TextArea.foreground",BODY);UIManager.put("ComboBox.background",SURFACE);UIManager.put("ComboBox.foreground",BODY);UIManager.put("List.background",SURFACE);UIManager.put("List.foreground",BODY);UIManager.put("List.selectionBackground",BLUE);UIManager.put("List.selectionForeground",Color.WHITE);UIManager.put("MenuBar.background",CARD);UIManager.put("MenuBar.foreground",INTERACTIVE);UIManager.put("MenuBar.font",new Font(Font.SANS_SERIF,Font.BOLD,13));UIManager.put("Menu.font",new Font(Font.SANS_SERIF,Font.BOLD,13));UIManager.put("Menu.background",CARD);UIManager.put("Menu.foreground",INTERACTIVE);UIManager.put("Menu.selectionBackground",SURFACE);UIManager.put("Menu.selectionForeground",Color.WHITE);UIManager.put("MenuItem.font",new Font(Font.SANS_SERIF,Font.BOLD,13));UIManager.put("MenuItem.background",CARD);UIManager.put("MenuItem.foreground",BODY);UIManager.put("MenuItem.selectionBackground",BLUE);UIManager.put("MenuItem.selectionForeground",Color.WHITE);UIManager.put("Table.background",CARD);UIManager.put("Table.foreground",BODY);UIManager.put("Table.selectionBackground",new Color(30,64,175));UIManager.put("Table.selectionForeground",Color.WHITE);UIManager.put("Table.gridColor",BORDER);UIManager.put("TableHeader.background",SURFACE);UIManager.put("TableHeader.foreground",HEADING);UIManager.put("TabbedPane.background",BG);UIManager.put("TabbedPane.foreground",INTERACTIVE);UIManager.put("TabbedPane.selected",SURFACE);UIManager.put("Viewport.background",CARD);UIManager.put("ScrollPane.background",CARD);UIManager.put("ScrollPane.border",BorderFactory.createLineBorder(BORDER));UIManager.put("ToolTip.background",NAVY_2);UIManager.put("ToolTip.foreground",Color.WHITE);UIManager.put("ToolTip.font",new Font(Font.SANS_SERIF,Font.BOLD,13));UIManager.put("ToolTip.border",BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(BLUE),new EmptyBorder(8,11,8,11)));}
 public static JButton button(String text,Color color){JButton b=new JButton(text);b.setFont(new Font(Font.SANS_SERIF,Font.BOLD,14));b.setForeground(Color.WHITE);b.setBackground(color);b.setOpaque(true);b.setContentAreaFilled(true);b.setBorderPainted(true);b.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(color.darker(),1),new EmptyBorder(11,18,11,18)));b.setMargin(new Insets(10,16,10,16));b.setMinimumSize(new Dimension(128,44));b.setPreferredSize(new Dimension(Math.max(128,b.getPreferredSize().width+12),44));b.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));b.setFocusPainted(true);b.getAccessibleContext().setAccessibleName(text);b.setToolTipText(text);Color hover=color.darker();b.getModel().addChangeListener(e->b.setBackground(b.getModel().isRollover()?hover:color));return b;}
 public static JButton secondaryButton(String text){JButton b=new JButton(text);b.setFont(new Font(Font.SANS_SERIF,Font.BOLD,14));b.setForeground(INTERACTIVE);b.setBackground(SURFACE);b.setOpaque(true);b.setContentAreaFilled(true);b.setBorderPainted(true);b.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(BORDER,1),new EmptyBorder(11,14,11,14)));b.setMinimumSize(new Dimension(150,46));b.setPreferredSize(new Dimension(Math.max(150,b.getPreferredSize().width+16),46));b.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));b.setFocusPainted(true);b.getAccessibleContext().setAccessibleName(text);b.setToolTipText(text);b.getModel().addChangeListener(e->b.setBackground(b.getModel().isRollover()?new Color(35,54,82):SURFACE));return b;}
 public static double contrastRatio(Color a,Color b){double x=luminance(a),y=luminance(b);return (Math.max(x,y)+.05)/(Math.min(x,y)+.05);}
 private static double luminance(Color c){double r=channel(c.getRed()/255.0),g=channel(c.getGreen()/255.0),b=channel(c.getBlue()/255.0);return .2126*r+.7152*g+.0722*b;}private static double channel(double c){return c<=.03928?c/12.92:Math.pow((c+.055)/1.055,2.4);}private static Color brighten(Color c){return new Color(Math.min(255,c.getRed()+18),Math.min(255,c.getGreen()+18),Math.min(255,c.getBlue()+18));}
 public static JLabel brandMark(){return new JLabel("Σ",SwingConstants.CENTER){private static final long serialVersionUID=1L;protected void paintComponent(Graphics g){Graphics2D q=(Graphics2D)g.create();q.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);q.setPaint(new GradientPaint(0,0,BLUE,getWidth(),getHeight(),CYAN));q.fillRoundRect(0,0,getWidth(),getHeight(),16,16);q.dispose();super.paintComponent(g);}};}
}
