package com.candyacademia.spsslite;
import javax.swing.*;import javax.swing.border.EmptyBorder;import java.awt.*;
public final class AppTheme {
 public static final Color NAVY=new Color(12,25,49),NAVY_2=new Color(20,39,72),BLUE=new Color(43,108,246),CYAN=new Color(41,190,207),BG=new Color(244,247,252),CARD=Color.WHITE,TEXT=new Color(31,41,55),MUTED=new Color(100,116,139),BORDER=new Color(220,227,238),SUCCESS=new Color(26,153,102);
 private AppTheme(){}
 public static void install(){UIManager.put("Panel.background",BG);UIManager.put("OptionPane.background",CARD);UIManager.put("OptionPane.messageForeground",TEXT);UIManager.put("Label.foreground",TEXT);UIManager.put("MenuBar.background",CARD);UIManager.put("Menu.background",CARD);UIManager.put("Menu.foreground",TEXT);UIManager.put("MenuItem.background",CARD);UIManager.put("MenuItem.foreground",TEXT);UIManager.put("MenuItem.selectionBackground",new Color(229,237,255));UIManager.put("MenuItem.selectionForeground",BLUE);UIManager.put("Table.selectionBackground",new Color(218,230,255));UIManager.put("Table.selectionForeground",TEXT);UIManager.put("Table.gridColor",new Color(232,237,245));UIManager.put("TabbedPane.selected",CARD);UIManager.put("ScrollPane.border",BorderFactory.createEmptyBorder());UIManager.put("ToolTip.background",NAVY);UIManager.put("ToolTip.foreground",Color.WHITE);UIManager.put("ToolTip.border",new EmptyBorder(7,10,7,10));}
 public static JButton button(String text,Color color){JButton b=new JButton(text);b.setFont(new Font(Font.SANS_SERIF,Font.BOLD,13));b.setForeground(Color.WHITE);b.setBackground(color);b.setOpaque(true);b.setBorder(new EmptyBorder(10,16,10,16));b.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));b.setFocusPainted(false);return b;}
 public static JLabel brandMark(){return new JLabel("Σ",SwingConstants.CENTER){private static final long serialVersionUID=1L;protected void paintComponent(Graphics g){Graphics2D q=(Graphics2D)g.create();q.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);q.setPaint(new GradientPaint(0,0,BLUE,getWidth(),getHeight(),CYAN));q.fillRoundRect(0,0,getWidth(),getHeight(),16,16);q.dispose();super.paintComponent(g);}};}
}
