package com.candyacademia.spsslite;
import javax.swing.*;import javax.swing.border.EmptyBorder;import java.awt.*;
public final class AppTheme {
 public static final Color NAVY=new Color(12,25,49),NAVY_2=new Color(20,39,72),BLUE=new Color(43,108,246),CYAN=new Color(41,190,207),BG=new Color(244,247,252),CARD=Color.WHITE,TEXT=new Color(31,41,55),MUTED=new Color(100,116,139),BORDER=new Color(220,227,238),SUCCESS=new Color(26,153,102);
 private AppTheme(){}
 public static void install(){Font buttonFont=new Font(Font.SANS_SERIF,Font.BOLD,14);UIManager.put("Panel.background",BG);UIManager.put("OptionPane.background",CARD);UIManager.put("OptionPane.messageForeground",TEXT);UIManager.put("Label.foreground",TEXT);UIManager.put("Button.font",buttonFont);UIManager.put("Button.foreground",TEXT);UIManager.put("Button.background",Color.WHITE);UIManager.put("Button.disabledText",MUTED);UIManager.put("Button.focus",new Color(147,197,253));UIManager.put("MenuBar.background",CARD);UIManager.put("MenuBar.font",new Font(Font.SANS_SERIF,Font.BOLD,13));UIManager.put("Menu.font",new Font(Font.SANS_SERIF,Font.BOLD,13));UIManager.put("Menu.background",CARD);UIManager.put("Menu.foreground",TEXT);UIManager.put("MenuItem.font",new Font(Font.SANS_SERIF,Font.PLAIN,13));UIManager.put("MenuItem.background",CARD);UIManager.put("MenuItem.foreground",TEXT);UIManager.put("MenuItem.selectionBackground",new Color(219,234,254));UIManager.put("MenuItem.selectionForeground",NAVY);UIManager.put("Table.selectionBackground",new Color(218,230,255));UIManager.put("Table.selectionForeground",TEXT);UIManager.put("Table.gridColor",new Color(232,237,245));UIManager.put("TabbedPane.selected",CARD);UIManager.put("ScrollPane.border",BorderFactory.createEmptyBorder());UIManager.put("ToolTip.background",NAVY);UIManager.put("ToolTip.foreground",Color.WHITE);UIManager.put("ToolTip.font",new Font(Font.SANS_SERIF,Font.PLAIN,13));UIManager.put("ToolTip.border",new EmptyBorder(8,11,8,11));}
 public static JButton button(String text,Color color){JButton b=new JButton(text);b.setFont(new Font(Font.SANS_SERIF,Font.BOLD,14));b.setForeground(Color.WHITE);b.setBackground(color);b.setOpaque(true);b.setContentAreaFilled(true);b.setBorderPainted(true);b.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(color.darker(),1),new EmptyBorder(11,18,11,18)));b.setMargin(new Insets(10,16,10,16));b.setMinimumSize(new Dimension(128,44));b.setPreferredSize(new Dimension(Math.max(128,b.getPreferredSize().width+12),44));b.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));b.setFocusPainted(true);b.getAccessibleContext().setAccessibleName(text);b.setToolTipText(text);Color hover=color.darker();b.getModel().addChangeListener(e->b.setBackground(b.getModel().isRollover()?hover:color));return b;}
 public static JButton secondaryButton(String text){JButton b=new JButton(text);b.setFont(new Font(Font.SANS_SERIF,Font.BOLD,14));b.setForeground(NAVY);b.setBackground(Color.WHITE);b.setOpaque(true);b.setContentAreaFilled(true);b.setBorderPainted(true);b.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(new Color(148,163,184),1),new EmptyBorder(11,14,11,14)));b.setMinimumSize(new Dimension(150,46));b.setPreferredSize(new Dimension(Math.max(150,b.getPreferredSize().width+16),46));b.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));b.setFocusPainted(true);b.getAccessibleContext().setAccessibleName(text);b.setToolTipText(text);b.getModel().addChangeListener(e->b.setBackground(b.getModel().isRollover()?new Color(226,236,255):Color.WHITE));return b;}
 public static double contrastRatio(Color a,Color b){double x=luminance(a),y=luminance(b);return (Math.max(x,y)+.05)/(Math.min(x,y)+.05);}
 private static double luminance(Color c){double r=channel(c.getRed()/255.0),g=channel(c.getGreen()/255.0),b=channel(c.getBlue()/255.0);return .2126*r+.7152*g+.0722*b;}private static double channel(double c){return c<=.03928?c/12.92:Math.pow((c+.055)/1.055,2.4);}private static Color brighten(Color c){return new Color(Math.min(255,c.getRed()+18),Math.min(255,c.getGreen()+18),Math.min(255,c.getBlue()+18));}
 public static JLabel brandMark(){return new JLabel("Σ",SwingConstants.CENTER){private static final long serialVersionUID=1L;protected void paintComponent(Graphics g){Graphics2D q=(Graphics2D)g.create();q.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);q.setPaint(new GradientPaint(0,0,BLUE,getWidth(),getHeight(),CYAN));q.fillRoundRect(0,0,getWidth(),getHeight(),16,16);q.dispose();super.paintComponent(g);}};}
}
