package com.candyacademia.spsslite;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;
import java.util.Arrays;

/** Sign-in, self-registration and recovery dialogs. */
public final class AuthenticationDialog {
    private AuthenticationDialog(){}
    public static String signIn(Component parent,UserAccountStore store){
        while(true){JTextField user=new JTextField(20);JPasswordField pass=new JPasswordField(20);JPanel fields=form("Welcome to Statistical Solutions",new String[]{"Username","Password"},new JComponent[]{user,pass});Object[]options={"Sign in","Create account","Forgot / Reset password","Exit"};int choice=JOptionPane.showOptionDialog(parent,fields,"Statistical Solutions — Sign in",JOptionPane.DEFAULT_OPTION,JOptionPane.PLAIN_MESSAGE,null,options,options[0]);
            if(choice==0){char[]secret=pass.getPassword();try{if(store.authenticate(user.getText(),secret))return store.displayName(user.getText());notice(parent,"Username or password is incorrect.",true);}catch(Exception e){notice(parent,e.getMessage(),true);}finally{Arrays.fill(secret,'\0');}}
            else if(choice==1)create(parent,store);else if(choice==2)forgot(parent,store);else return null;
        }
    }
    public static void changePassword(Component parent,UserAccountStore store,String username){JPasswordField current=new JPasswordField(),next=new JPasswordField(),confirm=new JPasswordField();JPanel p=form("Change password for "+username,new String[]{"Current password","New password","Confirm new password"},new JComponent[]{current,next,confirm});if(JOptionPane.showConfirmDialog(parent,p,"Change password",JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE)!=JOptionPane.OK_OPTION)return;char[]a=current.getPassword(),b=next.getPassword(),c=confirm.getPassword();try{if(!Arrays.equals(b,c))throw new IllegalArgumentException("New passwords do not match.");store.changePassword(username,a,b);notice(parent,"Password changed successfully.",false);}catch(Exception e){notice(parent,e.getMessage(),true);}finally{wipe(a,b,c);}}
    private static void create(Component parent,UserAccountStore store){JTextField user=new JTextField();JPasswordField pass=new JPasswordField(),confirm=new JPasswordField();JComboBox<String>question=new JComboBox<>(new String[]{"What was the name of your first school?","What city were you born in?","What is the name of your childhood friend?","What is your favourite book?"});JPasswordField answer=new JPasswordField();JPanel p=form("Create your local account",new String[]{"Username","Password","Confirm password","Security question","Recovery answer"},new JComponent[]{user,pass,confirm,question,answer});if(JOptionPane.showConfirmDialog(parent,p,"Create account",JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE)!=JOptionPane.OK_OPTION)return;char[]a=pass.getPassword(),b=confirm.getPassword(),c=answer.getPassword();try{if(!Arrays.equals(a,b))throw new IllegalArgumentException("Passwords do not match.");store.create(user.getText(),a,(String)question.getSelectedItem(),c);notice(parent,"Account created. You can now sign in.",false);}catch(Exception e){notice(parent,e.getMessage(),true);}finally{wipe(a,b,c);}}
    private static void forgot(Component parent,UserAccountStore store){String username=JOptionPane.showInputDialog(parent,"Enter your username:","Reset password",JOptionPane.PLAIN_MESSAGE);if(username==null||username.isBlank())return;String question=store.securityQuestion(username);if(question==null){notice(parent,"Username was not found.",true);return;}JPasswordField answer=new JPasswordField(),pass=new JPasswordField(),confirm=new JPasswordField();JPanel p=form(question,new String[]{"Recovery answer","New password","Confirm new password"},new JComponent[]{answer,pass,confirm});if(JOptionPane.showConfirmDialog(parent,p,"Forgot / Reset password",JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE)!=JOptionPane.OK_OPTION)return;char[]a=answer.getPassword(),b=pass.getPassword(),c=confirm.getPassword();try{if(!Arrays.equals(b,c))throw new IllegalArgumentException("New passwords do not match.");store.resetPassword(username,a,b);notice(parent,"Password reset successfully. You can now sign in.",false);}catch(Exception e){notice(parent,e.getMessage(),true);}finally{wipe(a,b,c);}}
    private static JPanel form(String heading,String[]labels,JComponent[]fields){JPanel root=new JPanel(new BorderLayout(0,14));root.setBorder(new EmptyBorder(18,20,18,20));JLabel title=new JLabel(heading);title.setFont(new Font(Font.SANS_SERIF,Font.BOLD,18));title.setForeground(AppTheme.HEADING);root.add(title,BorderLayout.NORTH);JPanel grid=new JPanel(new GridLayout(labels.length,2,10,10));for(int i=0;i<labels.length;i++){grid.add(new JLabel(labels[i]));grid.add(fields[i]);}root.add(grid);return root;}
    private static void notice(Component p,String message,boolean error){JOptionPane.showMessageDialog(p,message,"Statistical Solutions",error?JOptionPane.ERROR_MESSAGE:JOptionPane.INFORMATION_MESSAGE);}private static void wipe(char[]...values){for(char[]v:values)Arrays.fill(v,'\0');}
}
