package com.candyacademia.spsslite;
import javax.swing.table.DefaultTableModel;
import javax.xml.parsers.DocumentBuilderFactory;
import org.w3c.dom.*;
import java.io.*;import java.lang.reflect.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.util.*;import java.util.zip.*;
public final class DataExchange{
 private DataExchange(){}
 public static DefaultTableModel readXlsx(Path path)throws Exception{try(ZipFile zip=new ZipFile(path.toFile())){List<String>shared=new ArrayList<>();ZipEntry ss=zip.getEntry("xl/sharedStrings.xml");if(ss!=null){Document d=parse(zip.getInputStream(ss));NodeList si=d.getElementsByTagName("si");for(int i=0;i<si.getLength();i++)shared.add(si.item(i).getTextContent());}ZipEntry sheet=zip.getEntry("xl/worksheets/sheet1.xml");if(sheet==null)throw new IOException("The workbook has no readable first worksheet.");Document d=parse(zip.getInputStream(sheet));NodeList rows=d.getElementsByTagName("row");List<List<String>>table=new ArrayList<>();int max=0;for(int i=0;i<rows.getLength();i++){Element row=(Element)rows.item(i);TreeMap<Integer,String>cells=new TreeMap<>();NodeList cs=row.getElementsByTagName("c");for(int j=0;j<cs.getLength();j++){Element c=(Element)cs.item(j);int col=column(c.getAttribute("r"));String type=c.getAttribute("t"),value="";NodeList vs=c.getElementsByTagName("v");if("inlineStr".equals(type)){NodeList ts=c.getElementsByTagName("t");if(ts.getLength()>0)value=ts.item(0).getTextContent();}else if(vs.getLength()>0){value=vs.item(0).getTextContent();if("s".equals(type)){int n=Integer.parseInt(value);value=n<shared.size()?shared.get(n):value;}else if("b".equals(type))value="1".equals(value)?"TRUE":"FALSE";}cells.put(col,value);}int width=cells.isEmpty()?0:cells.lastKey()+1;max=Math.max(max,width);List<String>values=new ArrayList<>(Collections.nCopies(width,""));for(var e:cells.entrySet())values.set(e.getKey(),e.getValue());table.add(values);}if(table.isEmpty())throw new IOException("The worksheet is empty.");Object[]headers=new Object[max];for(int c=0;c<max;c++){String h=c<table.get(0).size()?table.get(0).get(c):"";headers[c]=h.isBlank()?"VAR"+(c+1):h;}DefaultTableModel model=new DefaultTableModel(headers,0);for(int r=1;r<table.size();r++){Object[]v=new Object[max];for(int c=0;c<max;c++)v[c]=c<table.get(r).size()?table.get(r).get(c):"";model.addRow(v);}return model;}}
 public static void writeXlsx(DefaultTableModel model,Path path)throws IOException{try(ZipOutputStream z=new ZipOutputStream(Files.newOutputStream(path))){entry(z,"[Content_Types].xml","<?xml version=\"1.0\" encoding=\"UTF-8\"?><Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\"><Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/><Default Extension=\"xml\" ContentType=\"application/xml\"/><Override PartName=\"/xl/workbook.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml\"/><Override PartName=\"/xl/worksheets/sheet1.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/></Types>");entry(z,"_rels/.rels","<?xml version=\"1.0\" encoding=\"UTF-8\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"xl/workbook.xml\"/></Relationships>");entry(z,"xl/workbook.xml","<?xml version=\"1.0\" encoding=\"UTF-8\"?><workbook xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\"><sheets><sheet name=\"Data\" sheetId=\"1\" r:id=\"rId1\"/></sheets></workbook>");entry(z,"xl/_rels/workbook.xml.rels","<?xml version=\"1.0\" encoding=\"UTF-8\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" Target=\"worksheets/sheet1.xml\"/></Relationships>");StringBuilder s=new StringBuilder("<?xml version=\"1.0\" encoding=\"UTF-8\"?><worksheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\"><sheetData>");s.append("<row r=\"1\">");for(int c=0;c<model.getColumnCount();c++)cell(s,c,1,model.getColumnName(c));s.append("</row>");for(int r=0;r<model.getRowCount();r++){s.append("<row r=\"").append(r+2).append("\">");for(int c=0;c<model.getColumnCount();c++)cell(s,c,r+2,model.getValueAt(r,c));s.append("</row>");}s.append("</sheetData></worksheet>");entry(z,"xl/worksheets/sheet1.xml",s.toString());}}
 public static DefaultTableModel readSav(Path path)throws Exception{Class<?>rc=Class.forName("com.bedatadriven.spss.SpssDataFileReader");Object reader=rc.getConstructor(String.class).newInstance(path.toString());List<?>vars=(List<?>)rc.getMethod("getVariables").invoke(reader);String[]headers=new String[vars.size()];boolean[]numeric=new boolean[vars.size()];Method name=rc.getMethod("getVariableName",int.class);for(int i=0;i<vars.size();i++){headers[i]=(String)name.invoke(reader,i);numeric[i]=(Boolean)vars.get(i).getClass().getMethod("isNumeric").invoke(vars.get(i));}DefaultTableModel model=new DefaultTableModel(headers,0);Method next=rc.getMethod("readNextCase"),number=rc.getMethod("getDoubleValue",int.class),text=rc.getMethod("getStringValue",int.class);while((Boolean)next.invoke(reader)){Object[]row=new Object[vars.size()];for(int i=0;i<row.length;i++){Object v=numeric[i]?number.invoke(reader,i):text.invoke(reader,i);row[i]=v instanceof Double&&Double.isNaN((Double)v)?"":v;}model.addRow(row);}return model;}
 public static Path writeSpssPackage(DefaultTableModel model,Path syntax)throws IOException{String n=syntax.getFileName().toString();if(!n.toLowerCase(Locale.ROOT).endsWith(".sps"))syntax=syntax.resolveSibling(n+".sps");Path csv=syntax.resolveSibling(syntax.getFileName().toString().replaceFirst("(?i)\\.sps$","-data.csv"));DataSet.writeCsv(model,csv);String file=csv.toAbsolutePath().toString().replace("\\","/").replace("'","''");StringBuilder vars=new StringBuilder();for(int i=0;i<model.getColumnCount();i++)vars.append("\n /").append(safeName(model.getColumnName(i))).append(" AUTO");String s="* Statistical Solutions SPSS import package.\nGET DATA\n /TYPE=TXT\n /FILE='"+file+"'\n /ENCODING='UTF8'\n /DELCASE=LINE\n /DELIMITERS=\",\"\n /QUALIFIER='\"'\n /ARRANGEMENT=DELIMITED\n /FIRSTCASE=2\n /VARIABLES="+vars+".\nEXECUTE.\nDATASET NAME StatisticalSolutions.\n";Files.writeString(syntax,s,StandardCharsets.UTF_8);return csv;}
 private static String safeName(String s){String n=s.replaceAll("[^A-Za-z0-9_@#$]","_");if(n.isEmpty()||Character.isDigit(n.charAt(0)))n="V_"+n;return n;}
 private static Document parse(InputStream in)throws Exception{DocumentBuilderFactory f=DocumentBuilderFactory.newInstance();f.setFeature("http://apache.org/xml/features/disallow-doctype-decl",true);return f.newDocumentBuilder().parse(in);}
 private static int column(String ref){int n=0;for(int i=0;i<ref.length()&&Character.isLetter(ref.charAt(i));i++)n=n*26+(Character.toUpperCase(ref.charAt(i))-'A'+1);return Math.max(0,n-1);}
 private static void cell(StringBuilder s,int c,int r,Object value){String ref=letters(c)+(r);String v=value==null?"":value.toString();try{double d=Double.parseDouble(v);if(Double.isFinite(d)){s.append("<c r=\"").append(ref).append("\"><v>").append(v).append("</v></c>");return;}}catch(Exception ignored){}s.append("<c r=\"").append(ref).append("\" t=\"inlineStr\"><is><t xml:space=\"preserve\">").append(xml(v)).append("</t></is></c>");}
 private static String letters(int n){StringBuilder s=new StringBuilder();do{s.insert(0,(char)('A'+n%26));n=n/26-1;}while(n>=0);return s.toString();}
 private static String xml(String s){return s.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;");}
 private static void entry(ZipOutputStream z,String name,String value)throws IOException{z.putNextEntry(new ZipEntry(name));z.write(value.getBytes(StandardCharsets.UTF_8));z.closeEntry();}
}
