package com.candyacademia.spsslite;
import javax.swing.*;import javax.swing.border.EmptyBorder;import javax.swing.table.*;import java.awt.*;import java.nio.file.*;import java.util.*;import java.util.List;
public final class Main extends JFrame{
 private static final long serialVersionUID=1L;private DefaultTableModel model=DataSet.blank(30,6);private final JTable table=new JTable(model);private final JTextArea output=new JTextArea();private final JLabel status=new JLabel("●  Ready"),counts=new JLabel();private final JTabbedPane tabs=new JTabbedPane();private Path current;
 public Main(){super("Statistical Solutions");setDefaultCloseOperation(EXIT_ON_CLOSE);setMinimumSize(new Dimension(1050,680));setSize(1240,800);setLocationRelativeTo(null);build();}
 private void build(){setLayout(new BorderLayout());configureTable();configureOutput();setJMenuBar(menu());add(header(),BorderLayout.NORTH);add(workspace(),BorderLayout.CENTER);add(statusBar(),BorderLayout.SOUTH);refreshCounts();}
 private JPanel header(){JPanel p=new JPanel(new BorderLayout(20,0));p.setBackground(AppTheme.NAVY);p.setBorder(new EmptyBorder(18,24,18,24));JLabel mark=AppTheme.brandMark();mark.setPreferredSize(new Dimension(48,48));mark.setForeground(Color.WHITE);mark.setFont(new Font(Font.SANS_SERIF,Font.BOLD,27));JPanel id=new JPanel(new BorderLayout());id.setOpaque(false);JLabel title=new JLabel("Statistical Solutions"),sub=new JLabel("Data clarity. Confident decisions.");title.setForeground(Color.WHITE);title.setFont(new Font(Font.SANS_SERIF,Font.BOLD,24));sub.setForeground(new Color(173,190,218));sub.setFont(new Font(Font.SANS_SERIF,Font.PLAIN,12));id.add(title);id.add(sub,BorderLayout.SOUTH);JPanel brand=new JPanel(new BorderLayout(14,0));brand.setOpaque(false);brand.add(mark,BorderLayout.WEST);brand.add(id);JPanel actions=new JPanel(new FlowLayout(FlowLayout.RIGHT,10,3));actions.setOpaque(false);JButton open=AppTheme.button("Open CSV",AppTheme.BLUE),save=AppTheme.button("Save Data",AppTheme.NAVY_2);open.addActionListener(e->open());save.addActionListener(e->save(false));actions.add(open);actions.add(save);p.add(brand,BorderLayout.WEST);p.add(actions,BorderLayout.EAST);return p;}
 private JComponent workspace(){JPanel root=new JPanel(new BorderLayout(16,16));root.setBorder(new EmptyBorder(18,22,14,22));root.setBackground(AppTheme.BG);root.add(quickActions(),BorderLayout.NORTH);tabs.setFont(new Font(Font.SANS_SERIF,Font.BOLD,13));tabs.setBorder(BorderFactory.createLineBorder(AppTheme.BORDER));tabs.addTab("  Data Editor  ",new JScrollPane(table));tabs.addTab("  Analysis Output  ",outputCard());root.add(tabs);return root;}
 private JPanel quickActions(){JPanel row=new JPanel(new FlowLayout(FlowLayout.LEFT,9,0));row.setOpaque(false);row.add(action("Explore",e->explore()));row.add(action("Frequencies",e->frequencies()));row.add(action("ANOVA",e->anova()));row.add(action("Non-parametric",e->mannWhitney()));row.add(action("Correlations",e->spearman()));row.add(action("Regression",e->multipleRegression()));row.add(action("Histogram",e->histogram()));return row;}
 private JButton action(String text,java.awt.event.ActionListener a){JButton b=new JButton(text);b.addActionListener(a);b.setFont(new Font(Font.SANS_SERIF,Font.BOLD,12));b.setForeground(AppTheme.TEXT);b.setBackground(Color.WHITE);b.setFocusPainted(false);b.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));b.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(AppTheme.BORDER),new EmptyBorder(9,14,9,14)));return b;}
 private JPanel outputCard(){JPanel p=new JPanel(new BorderLayout());p.setBackground(Color.WHITE);p.setBorder(new EmptyBorder(12,12,12,12));JPanel top=new JPanel(new BorderLayout());top.setBackground(Color.WHITE);top.setBorder(new EmptyBorder(0,4,10,4));JLabel h=new JLabel("Analysis results");h.setFont(new Font(Font.SANS_SERIF,Font.BOLD,18));top.add(h);top.add(action("Export report",e->exportOutput()),BorderLayout.EAST);p.add(top,BorderLayout.NORTH);p.add(new JScrollPane(output));return p;}
 private JPanel statusBar(){JPanel p=new JPanel(new BorderLayout());p.setBackground(Color.WHITE);p.setBorder(new EmptyBorder(9,22,9,22));status.setForeground(AppTheme.SUCCESS);status.setFont(new Font(Font.SANS_SERIF,Font.BOLD,12));counts.setForeground(AppTheme.MUTED);p.add(status,BorderLayout.WEST);p.add(counts,BorderLayout.EAST);return p;}
 private void configureTable(){table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);table.setCellSelectionEnabled(true);table.setRowHeight(30);table.setFont(new Font(Font.SANS_SERIF,Font.PLAIN,13));table.setForeground(AppTheme.TEXT);table.setBackground(Color.WHITE);table.setShowVerticalLines(false);table.setIntercellSpacing(new Dimension(0,1));table.setFillsViewportHeight(true);table.getTableHeader().setPreferredSize(new Dimension(0,36));table.getTableHeader().setFont(new Font(Font.SANS_SERIF,Font.BOLD,12));table.getTableHeader().setBackground(AppTheme.NAVY_2);table.getTableHeader().setForeground(Color.WHITE);table.setDefaultRenderer(Object.class,new DefaultTableCellRenderer(){private static final long serialVersionUID=1L;public Component getTableCellRendererComponent(JTable t,Object v,boolean selected,boolean focus,int row,int col){Component c=super.getTableCellRendererComponent(t,v,selected,focus,row,col);if(!selected)c.setBackground(row%2==0?Color.WHITE:new Color(248,250,253));setBorder(new EmptyBorder(0,10,0,10));return c;}});model.addTableModelListener(e->refreshCounts());}
 private void configureOutput(){output.setEditable(false);output.setFont(new Font(Font.MONOSPACED,Font.PLAIN,13));output.setForeground(AppTheme.TEXT);output.setBackground(new Color(251,252,254));output.setMargin(new Insets(18,18,18,18));output.setText("STATISTICAL SOLUTIONS\nAnalysis output will appear here.\n\nChoose a procedure from the quick-action bar above.");}
 private JMenuBar menu(){JMenuBar b=new JMenuBar();b.setBorder(new EmptyBorder(4,12,4,12));JMenu file=new JMenu("File"),data=new JMenu("Data"),an=new JMenu("Analyze"),nonp=new JMenu("Non-parametric"),models=new JMenu("Models"),graphs=new JMenu("Graphs");item(file,"New dataset",e->setModel(DataSet.blank(30,6)));item(file,"Open CSV…",e->open());item(file,"Save CSV",e->save(false));item(file,"Save CSV As…",e->save(true));item(file,"Export output…",e->exportOutput());item(file,"Exit",e->dispose());item(data,"Add case",e->{model.addRow(new Object[model.getColumnCount()]);setStatus("Case added");});item(data,"Add variable",e->{model.addColumn("VAR"+(model.getColumnCount()+1));setStatus("Variable added");});item(data,"Rename variable…",e->rename());item(data,"Standardize as Z-score…",e->zScores());item(an,"Explore and Normality…",e->explore());item(an,"Frequency Distribution…",e->frequencies());item(an,"Missing-Data Summary",e->missingSummary());item(an,"Descriptive Statistics…",e->descriptive());item(an,"One-Sample t Test…",e->oneSampleT());item(an,"Paired-Samples t Test…",e->pairedT());item(an,"Independent-Samples t Test…",e->ttest());item(an,"One-Way ANOVA…",e->anova());item(an,"Pearson Correlation…",e->correlation());item(an,"Spearman and Kendall…",e->spearman());item(an,"Chi-Square Test…",e->chiSquare());item(nonp,"Mann–Whitney U…",e->mannWhitney());item(nonp,"Wilcoxon Signed-Rank…",e->wilcoxon());item(nonp,"Kruskal–Wallis H…",e->kruskalWallis());item(models,"Simple Linear Regression…",e->regression());item(models,"Multiple Linear Regression…",e->multipleRegression());item(graphs,"Histogram…",e->histogram());b.add(file);b.add(data);b.add(an);b.add(nonp);b.add(models);b.add(graphs);return b;}
 private void item(JMenu m,String n,java.awt.event.ActionListener a){JMenuItem i=new JMenuItem(n);i.setBorder(new EmptyBorder(8,12,8,20));i.addActionListener(a);m.add(i);}
 private void setModel(DefaultTableModel m){model=m;table.setModel(m);configureTable();current=null;refreshCounts();setStatus("New dataset ready");}
 private void open(){JFileChooser f=new JFileChooser();if(f.showOpenDialog(this)==JFileChooser.APPROVE_OPTION)try{Path p=f.getSelectedFile().toPath();setModel(DataSet.readCsv(p));current=p;setStatus("Opened "+p.getFileName());}catch(Exception e){error(e);}}
 private void save(boolean as){try{if(as||current==null){JFileChooser f=new JFileChooser();if(f.showSaveDialog(this)!=JFileChooser.APPROVE_OPTION)return;current=f.getSelectedFile().toPath();}DataSet.writeCsv(model,current);setStatus("Saved "+current.getFileName());}catch(Exception e){error(e);}}
 private void exportOutput(){JFileChooser f=new JFileChooser();if(f.showSaveDialog(this)==JFileChooser.APPROVE_OPTION)try{Files.writeString(f.getSelectedFile().toPath(),output.getText());setStatus("Report exported");}catch(Exception e){error(e);}}
 private void rename(){int c=table.getSelectedColumn();if(c<0){message("Select a column first.");return;}String s=JOptionPane.showInputDialog(this,"New variable name:",model.getColumnName(c));if(s!=null&&!s.isBlank()){model.setColumnIdentifiers(headersWith(c,s.trim()));setStatus("Variable renamed");}}
 private Object[] headersWith(int c,String n){Object[] h=new Object[model.getColumnCount()];for(int i=0;i<h.length;i++)h[i]=i==c?n:model.getColumnName(i);return h;}
 private JComboBox<String> combo(){JComboBox<String> c=new JComboBox<>();for(int i=0;i<model.getColumnCount();i++)c.addItem(model.getColumnName(i));return c;}
 private int chooseOne(String title){JComboBox<String> c=combo();c.setPreferredSize(new Dimension(260,32));return JOptionPane.showConfirmDialog(this,c,title,JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION?c.getSelectedIndex():-1;}
 private int[] chooseTwo(String title,String a,String b){JComboBox<String>x=combo(),y=combo();if(model.getColumnCount()>1)y.setSelectedIndex(1);JPanel p=new JPanel(new GridLayout(2,2,8,8));p.setBorder(new EmptyBorder(8,8,8,8));p.add(new JLabel(a));p.add(x);p.add(new JLabel(b));p.add(y);return JOptionPane.showConfirmDialog(this,p,title,JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION?new int[]{x.getSelectedIndex(),y.getSelectedIndex()}:null;}
 private void explore(){int c=chooseOne("Explore numeric variable");if(c<0)return;var d=PhaseOneStatistics.explore(DataSet.numeric(model,c),model.getRowCount());append("EXPLORE AND NORMALITY\nVariable: %s\nN=%d  Missing=%d\nMean=%.6f  Std. Error=%.6f  95%% CI=[%.6f, %.6f]\nVariance=%.6f  Std. Deviation=%.6f\nMedian=%.6f  Q1=%.6f  Q3=%.6f  IQR=%.6f\nMinimum=%.6f  Maximum=%.6f  Range=%.6f\nSkewness=%.6f  Excess Kurtosis=%.6f\nJarque-Bera=%.6f  Approx. p=%.6g\nOutlier fences=[%.6f, %.6f]\n".formatted(name(c),d.n(),d.missing(),d.mean(),d.se(),d.ciLow(),d.ciHigh(),d.variance(),d.sd(),d.median(),d.q1(),d.q3(),d.iqr(),d.min(),d.max(),d.range(),d.skewness(),d.excessKurtosis(),d.jarqueBera(),d.normalityP(),d.q1()-1.5*d.iqr(),d.q3()+1.5*d.iqr()));}
 private void frequencies(){int c=chooseOne("Select frequency variable");if(c<0)return;List<String>v=new ArrayList<>();for(int r=0;r<model.getRowCount();r++)v.add(DataSet.text(model,r,c));var f=PhaseOneStatistics.frequencies(v,model.getRowCount());StringBuilder s=new StringBuilder("FREQUENCY DISTRIBUTION\nVariable: ").append(name(c)).append("\nValue\tFrequency\tPercent\tValid %\tCumulative %\n");for(var x:f)s.append(String.format("%s\t%d\t%.2f\t%.2f\t%.2f\n",x.value(),x.count(),x.percent(),x.validPercent(),x.cumulativePercent()));append(s.toString());}
 private void missingSummary(){append(PhaseOneStatistics.missingSummary(model));}
 private void oneSampleT(){int c=chooseOne("One-sample t test: select numeric variable");if(c<0)return;String input=JOptionPane.showInputDialog(this,"Test value:","0");if(input==null)return;try{double mu=Double.parseDouble(input.trim());double[]a=DataSet.numeric(model,c).stream().mapToDouble(Double::doubleValue).toArray();var t=PhaseOneStatistics.oneSample(a,mu);append("ONE-SAMPLE t TEST\nVariable: %s  |  Test value: %.6f\nN=%d  Mean=%.6f  Mean difference=%.6f\nt=%.6f  df=%.0f  p=%.6g\n95%% CI of difference=[%.6f, %.6f]\nCohen's d=%.6f\n".formatted(name(c),t.testValue(),t.n(),t.mean(),t.difference(),t.t(),t.df(),t.p(),t.ciLow(),t.ciHigh(),t.cohenD()));}catch(Exception e){error(e);}}
 private void pairedT(){int[]c=chooseTwo("Paired-samples t test","Measurement 1","Measurement 2");if(c==null)return;try{double[][]p=DataSet.paired(model,c[0],c[1]);var t=PhaseOneStatistics.paired(p[0],p[1]);append("PAIRED-SAMPLES t TEST\nPair: %s − %s\nN=%d  Mean 1=%.6f  Mean 2=%.6f\nMean difference=%.6f  SD difference=%.6f\nt=%.6f  df=%.0f  p=%.6g\n95%% CI of difference=[%.6f, %.6f]\nCohen's dz=%.6f\n".formatted(name(c[0]),name(c[1]),t.n(),t.mean1(),t.mean2(),t.meanDifference(),t.sdDifference(),t.t(),t.df(),t.p(),t.ciLow(),t.ciHigh(),t.cohenDz()));}catch(Exception e){error(e);}}
 private void zScores(){int c=chooseOne("Standardize numeric variable");if(c<0)return;try{PhaseOneStatistics.appendZScores(model,c);refreshCounts();setStatus("Z-score variable created");}catch(Exception e){error(e);}}
 private void descriptive(){int c=chooseOne("Select numeric variable");if(c<0)return;var d=Statistics.describe(DataSet.numeric(model,c),model.getRowCount());append("DESCRIPTIVE STATISTICS\nVariable: %s\nN=%d  Missing=%d\nMean=%.6f  Median=%.6f  Std. Deviation=%.6f\nMinimum=%.6f  Maximum=%.6f\n".formatted(name(c),d.n(),d.missing(),d.mean(),d.median(),d.sd(),d.min(),d.max()));}
 private Map<String,List<Double>> groups(int outcome,int group){Map<String,List<Double>>g=new LinkedHashMap<>();for(int r=0;r<model.getRowCount();r++)try{String v=DataSet.text(model,r,outcome),k=DataSet.text(model,r,group);if(!v.isBlank()&&!k.isBlank())g.computeIfAbsent(k,z->new ArrayList<>()).add(Double.parseDouble(v));}catch(NumberFormatException ignored){}return g;}
 private void anova(){int[]c=chooseTwo("One-way ANOVA","Numeric outcome","Factor / group");if(c==null)return;try{Map<String,List<Double>>g=groups(c[0],c[1]);var a=PhaseTwoStatistics.anova(g.values().stream().map(v->v.stream().mapToDouble(Double::doubleValue).toArray()).toList());StringBuilder s=new StringBuilder("ONE-WAY ANOVA\nOutcome: ").append(name(c[0])).append(" | Factor: ").append(name(c[1])).append("\nGroup\tN\tMean\tSD\n");for(var e:g.entrySet()){double[]v=e.getValue().stream().mapToDouble(Double::doubleValue).toArray();double m=Arrays.stream(v).average().orElse(Double.NaN),ss=0;for(double x:v)ss+=(x-m)*(x-m);s.append(String.format("%s\t%d\t%.6f\t%.6f\n",e.getKey(),v.length,m,v.length>1?Math.sqrt(ss/(v.length-1)):0));}s.append(String.format("\nSource\tSS\tdf\tMS\tF\tp\nBetween\t%.6f\t%d\t%.6f\t%.6f\t%.6g\nWithin\t%.6f\t%d\t%.6f\nEta squared=%.6f\n",a.ssBetween(),a.dfBetween(),a.msBetween(),a.f(),a.p(),a.ssWithin(),a.dfWithin(),a.msWithin(),a.etaSquared()));append(s.toString());}catch(Exception e){error(e);}}
 private void spearman(){int[]c=chooseTwo("Rank correlations","Variable 1","Variable 2");if(c==null)return;double[][]p=DataSet.paired(model,c[0],c[1]);append("RANK CORRELATIONS\n%s × %s\nN=%d\nSpearman rho=%.6f\nKendall tau-b=%.6f\n".formatted(name(c[0]),name(c[1]),p[0].length,PhaseTwoStatistics.spearman(p[0],p[1]),PhaseTwoStatistics.kendallTauB(p[0],p[1])));}
 private void mannWhitney(){int[]c=chooseTwo("Mann–Whitney U test","Numeric outcome","Group (exactly 2 groups)");if(c==null)return;try{Map<String,List<Double>>g=groups(c[0],c[1]);if(g.size()!=2)throw new IllegalArgumentException("The grouping variable must contain exactly 2 groups.");var it=g.entrySet().iterator();var a=it.next();var b=it.next();var z=PhaseTwoStatistics.mannWhitney(a.getValue().stream().mapToDouble(Double::doubleValue).toArray(),b.getValue().stream().mapToDouble(Double::doubleValue).toArray());append("MANN–WHITNEY U TEST\nOutcome: %s | %s (N=%d) vs %s (N=%d)\nU=%.6f  z=%.6f  p=%.6g\nEffect size r=%.6f\n".formatted(name(c[0]),a.getKey(),a.getValue().size(),b.getKey(),b.getValue().size(),z.statistic(),z.z(),z.p(),z.effectSize()));}catch(Exception e){error(e);}}
 private void wilcoxon(){int[]c=chooseTwo("Wilcoxon signed-rank test","Measurement 1","Measurement 2");if(c==null)return;try{double[][]p=DataSet.paired(model,c[0],c[1]);var z=PhaseTwoStatistics.wilcoxon(p[0],p[1]);append("WILCOXON SIGNED-RANK TEST\nPair: %s − %s\nN=%d  W=%.6f  z=%.6f  p=%.6g\nEffect size r=%.6f\n".formatted(name(c[0]),name(c[1]),p[0].length,z.statistic(),z.z(),z.p(),z.effectSize()));}catch(Exception e){error(e);}}
 private void kruskalWallis(){int[]c=chooseTwo("Kruskal–Wallis test","Numeric outcome","Group factor");if(c==null)return;try{Map<String,List<Double>>g=groups(c[0],c[1]);var z=PhaseTwoStatistics.kruskalWallis(g.values().stream().map(v->v.stream().mapToDouble(Double::doubleValue).toArray()).toList());append("KRUSKAL–WALLIS TEST\nOutcome: %s | Factor: %s | Groups=%d\nH=%.6f  df=%d  p=%.6g\nEpsilon-squared approximation=%.6f\n".formatted(name(c[0]),name(c[1]),g.size(),z.statistic(),z.df(),z.p(),z.effectSize()));}catch(Exception e){error(e);}}
 private void multipleRegression(){JComboBox<String>outcome=combo();DefaultListModel<String>lm=new DefaultListModel<>();for(int i=0;i<model.getColumnCount();i++)lm.addElement(name(i));JList<String>predictors=new JList<>(lm);predictors.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);predictors.setVisibleRowCount(Math.min(7,model.getColumnCount()));JPanel p=new JPanel(new BorderLayout(8,8));p.add(new JLabel("Outcome variable:"),BorderLayout.NORTH);p.add(outcome,BorderLayout.CENTER);JPanel lower=new JPanel(new BorderLayout());lower.add(new JLabel("Predictors (Ctrl-click to select multiple):"),BorderLayout.NORTH);lower.add(new JScrollPane(predictors));p.add(lower,BorderLayout.SOUTH);if(JOptionPane.showConfirmDialog(this,p,"Multiple linear regression",JOptionPane.OK_CANCEL_OPTION)!=JOptionPane.OK_OPTION)return;int ycol=outcome.getSelectedIndex();int[]xcols=predictors.getSelectedIndices();if(xcols.length<1){message("Select at least one predictor.");return;}for(int x:xcols)if(x==ycol){message("The outcome cannot also be a predictor.");return;}try{List<double[]>rows=new ArrayList<>();List<Double>ys=new ArrayList<>();for(int r=0;r<model.getRowCount();r++)try{String sy=DataSet.text(model,r,ycol);if(sy.isBlank())continue;double[]row=new double[xcols.length];boolean ok=true;for(int j=0;j<xcols.length;j++){String sx=DataSet.text(model,r,xcols[j]);if(sx.isBlank()){ok=false;break;}row[j]=Double.parseDouble(sx);}if(ok){rows.add(row);ys.add(Double.parseDouble(sy));}}catch(NumberFormatException ignored){}var m=PhaseTwoStatistics.multipleRegression(rows.toArray(double[][]::new),ys.stream().mapToDouble(Double::doubleValue).toArray());StringBuilder s=new StringBuilder("MULTIPLE LINEAR REGRESSION\nOutcome: ").append(name(ycol)).append("\nN=").append(m.n()).append(String.format("  R²=%.6f  Adjusted R²=%.6f  Std. Error=%.6f\nF=%.6f  Model p=%.6g\n\nCoefficient\tB\tSE\tt\tp\n",m.r2(),m.adjustedR2(),m.standardError(),m.f(),m.modelP()));for(int j=0;j<m.coefficients().length;j++)s.append(String.format("%s\t%.6f\t%.6f\t%.6f\t%.6g\n",j==0?"Intercept":name(xcols[j-1]),m.coefficients()[j],m.standardErrors()[j],m.t()[j],m.p()[j]));append(s.toString());}catch(Exception e){error(e);}}
 private void correlation(){int[]c=chooseTwo("Pearson correlation","Variable 1","Variable 2");if(c==null)return;double[][]p=DataSet.paired(model,c[0],c[1]);append("PEARSON CORRELATION\n%s × %s\nN=%d  r=%.6f\n".formatted(name(c[0]),name(c[1]),p[0].length,Statistics.correlation(p[0],p[1])));}
 private void regression(){int[]c=chooseTwo("Simple linear regression","Predictor (X)","Outcome (Y)");if(c==null)return;try{double[][]p=DataSet.paired(model,c[0],c[1]);var r=Statistics.regression(p[0],p[1]);append("SIMPLE LINEAR REGRESSION\nOutcome: %s | Predictor: %s\nN=%d  R=%.6f  R²=%.6f  Std. error=%.6f\nIntercept=%.6f  B=%.6f  t=%.6f  p=%.6g\nEquation: %s = %.6f + %.6f(%s)\n".formatted(name(c[1]),name(c[0]),r.n(),r.r(),r.r2(),r.se(),r.intercept(),r.slope(),r.t(),r.p(),name(c[1]),r.intercept(),r.slope(),name(c[0])));}catch(Exception e){error(e);}}
 private void ttest(){int[]c=chooseTwo("Independent-samples t test","Numeric outcome","Group variable (exactly 2 groups)");if(c==null)return;Map<String,List<Double>>g=new LinkedHashMap<>();for(int r=0;r<model.getRowCount();r++)try{String v=DataSet.text(model,r,c[0]),k=DataSet.text(model,r,c[1]);if(!v.isBlank()&&!k.isBlank())g.computeIfAbsent(k,z->new ArrayList<>()).add(Double.parseDouble(v));}catch(NumberFormatException ignored){}if(g.size()!=2){message("The grouping variable must contain exactly 2 non-empty groups.");return;}var it=g.entrySet().iterator();var a=it.next();var d=it.next();try{var t=Statistics.welch(a.getValue().stream().mapToDouble(Double::doubleValue).toArray(),d.getValue().stream().mapToDouble(Double::doubleValue).toArray());append("WELCH INDEPENDENT-SAMPLES t TEST\nOutcome: %s | Groups: %s vs %s\n%s: N=%d Mean=%.6f\n%s: N=%d Mean=%.6f\nt=%.6f  df=%.3f  p=%.6g\n".formatted(name(c[0]),a.getKey(),d.getKey(),a.getKey(),t.n1(),t.mean1(),d.getKey(),t.n2(),t.mean2(),t.t(),t.df(),t.p()));}catch(Exception e){error(e);}}
 private void chiSquare(){int[]c=chooseTwo("Chi-square test of independence","Row variable","Column variable");if(c==null)return;List<String>a=new ArrayList<>(),b=new ArrayList<>();for(int r=0;r<model.getRowCount();r++){String x=DataSet.text(model,r,c[0]),y=DataSet.text(model,r,c[1]);if(!x.isBlank()&&!y.isBlank()){a.add(x);b.add(y);}}try{var z=Statistics.chiSquare(a,b);StringBuilder s=new StringBuilder("CHI-SQUARE TEST OF INDEPENDENCE\n").append(name(c[0])).append(" × ").append(name(c[1])).append('\n');s.append(String.format("χ²=%.6f  df=%d  p=%.6g  N=%d\n",z.statistic(),z.df(),z.p(),a.size()));s.append("Observed counts:\n\t").append(String.join("\t",z.cols())).append('\n');for(int i=0;i<z.rows().length;i++){s.append(z.rows()[i]);for(int v:z.observed()[i])s.append('\t').append(v);s.append('\n');}append(s.toString());}catch(Exception e){error(e);}}
 private void histogram(){int c=chooseOne("Select numeric variable");if(c<0)return;JDialog d=new JDialog(this,"Histogram — "+name(c),false);d.add(new ChartPanel(name(c),DataSet.numeric(model,c)));d.pack();d.setLocationRelativeTo(this);d.setVisible(true);setStatus("Histogram created");}
 private String name(int c){return model.getColumnName(c);}private void append(String s){if(output.getText().startsWith("STATISTICAL SOLUTIONS"))output.setText("");output.append("\n"+s+"\n");output.setCaretPosition(output.getDocument().getLength());tabs.setSelectedIndex(1);setStatus("Analysis completed");}
 private void refreshCounts(){counts.setText(model.getRowCount()+" cases   •   "+model.getColumnCount()+" variables");}private void setStatus(String s){status.setText("●  "+s);}private void message(String s){JOptionPane.showMessageDialog(this,s,"Statistical Solutions",JOptionPane.INFORMATION_MESSAGE);}private void error(Exception e){JOptionPane.showMessageDialog(this,e.getMessage(),"Unable to complete action",JOptionPane.ERROR_MESSAGE);setStatus("Action needs attention");}
 public static void main(String[]args){SwingUtilities.invokeLater(()->{try{UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());}catch(Exception ignored){}AppTheme.install();new Main().setVisible(true);});}
}
