package com.candyacademia.spsslite;

import java.util.*;

/** Phase 5: advanced modelling, classification validation and repeated measures. */
public final class PhaseFiveStatistics {
    private PhaseFiveStatistics() {}
    public record RepeatedMeasures(int subjects,int conditions,double ssConditions,double ssSubjects,double ssError,int dfConditions,int dfSubjects,int dfError,double msConditions,double msError,double f,double p,double partialEtaSquared,double[] means) {}
    public record RocPoint(double threshold,double sensitivity,double specificity,double falsePositiveRate) {}
    public record ROC(int n,int positives,int negatives,double auc,double standardError,double ciLow,double ciHigh,double optimalThreshold,double optimalSensitivity,double optimalSpecificity,RocPoint[] points) {}
    public record Poisson(int n,int predictors,int iterations,boolean converged,double logLikelihood,double deviance,double pearsonChiSquare,double modelChiSquare,double modelP,double pseudoR2,double[] coefficients,double[] standardErrors,double[] wald,double[] p,double[] incidenceRateRatios) {}
    public record Diagnostics(int n,int predictors,double r2,double adjustedR2,double standardError,double[] coefficients,double[] predicted,double[] residuals,double[] standardizedResiduals,double[] leverage,double[] cooksDistance) {}

    public static RepeatedMeasures repeatedMeasures(double[][]x){
        if(x.length<2||x[0].length<2)throw new IllegalArgumentException("Select at least 2 subjects and 2 repeated measurements.");int n=x.length,k=x[0].length;double grand=0;double[]cm=new double[k],rm=new double[n];
        for(int i=0;i<n;i++){if(x[i].length!=k)throw new IllegalArgumentException("Rows have inconsistent lengths.");for(int j=0;j<k;j++){if(!Double.isFinite(x[i][j]))throw new IllegalArgumentException("Measurements must be finite.");grand+=x[i][j];cm[j]+=x[i][j];rm[i]+=x[i][j];}}
        grand/=n*k;for(int j=0;j<k;j++)cm[j]/=n;for(int i=0;i<n;i++)rm[i]/=k;double total=0,ssc=0,sss=0;for(int i=0;i<n;i++)for(int j=0;j<k;j++)total+=sq(x[i][j]-grand);for(double v:cm)ssc+=n*sq(v-grand);for(double v:rm)sss+=k*sq(v-grand);double sse=Math.max(0,total-ssc-sss);int dfc=k-1,dfs=n-1,dfe=dfc*dfs;double msc=ssc/dfc,mse=sse/dfe,f=mse==0?Double.POSITIVE_INFINITY:msc/mse,p=Double.isFinite(f)?fSurvival(f,dfc,dfe):0;return new RepeatedMeasures(n,k,ssc,sss,sse,dfc,dfs,dfe,msc,mse,f,p,ssc/(ssc+sse),cm);
    }

    public static ROC roc(double[]score,int[]actual){
        if(score.length!=actual.length||score.length<4)throw new IllegalArgumentException("At least 4 paired observations are required.");int pos=0;for(int i=0;i<score.length;i++){if(!Double.isFinite(score[i]))throw new IllegalArgumentException("Scores must be finite.");if(actual[i]!=0&&actual[i]!=1)throw new IllegalArgumentException("Actual outcome must be coded 0 and 1.");pos+=actual[i];}int neg=score.length-pos;if(pos==0||neg==0)throw new IllegalArgumentException("Actual outcome must contain both 0 and 1.");
        TreeSet<Double>cuts=new TreeSet<>(Comparator.reverseOrder());for(double v:score)cuts.add(v);List<RocPoint>points=new ArrayList<>();points.add(new RocPoint(Double.POSITIVE_INFINITY,0,1,0));double best=-Double.MAX_VALUE,bcut=Double.NaN,bsens=0,bspec=0;
        for(double cut:cuts){int tp=0,fp=0;for(int i=0;i<score.length;i++)if(score[i]>=cut){if(actual[i]==1)tp++;else fp++;}double sens=(double)tp/pos,spec=1-(double)fp/neg,youden=sens+spec-1;points.add(new RocPoint(cut,sens,spec,1-spec));if(youden>best){best=youden;bcut=cut;bsens=sens;bspec=spec;}}
        points.add(new RocPoint(Double.NEGATIVE_INFINITY,1,0,1));double auc=0;for(int i=1;i<points.size();i++){RocPoint a=points.get(i-1),b=points.get(i);auc+=(b.falsePositiveRate()-a.falsePositiveRate())*(a.sensitivity()+b.sensitivity())/2;}double q1=auc/(2-auc),q2=2*auc*auc/(1+auc),se=Math.sqrt((auc*(1-auc)+(pos-1)*(q1-auc*auc)+(neg-1)*(q2-auc*auc))/(pos*neg));return new ROC(score.length,pos,neg,auc,se,Math.max(0,auc-1.96*se),Math.min(1,auc+1.96*se),bcut,bsens,bspec,points.toArray(RocPoint[]::new));
    }

    public static Poisson poisson(double[][]x,int[]y,int maxIterations){
        if(x.length!=y.length||x.length<4)throw new IllegalArgumentException("At least 4 complete observations are required.");int n=x.length,k=x[0].length+1,total=0;for(int i=0;i<n;i++){if(x[i].length!=k-1)throw new IllegalArgumentException("Predictor rows have inconsistent lengths.");if(y[i]<0)throw new IllegalArgumentException("Counts must be non-negative integers.");total+=y[i];}if(total==0)throw new IllegalArgumentException("At least one positive count is required.");double[]b=new double[k];b[0]=Math.log((double)total/n);boolean converged=false;int iterations=0;double[][]info=null;
        for(int it=0;it<maxIterations;it++){iterations=it+1;double[]score=new double[k];info=new double[k][k];for(int i=0;i<n;i++){double eta=b[0];for(int j=1;j<k;j++)eta+=b[j]*x[i][j-1];double mu=Math.exp(Math.max(-30,Math.min(30,eta)));for(int a=0;a<k;a++){double za=a==0?1:x[i][a-1];score[a]+=za*(y[i]-mu);for(int c=0;c<k;c++){double zc=c==0?1:x[i][c-1];info[a][c]+=mu*za*zc;}}}double[]step=multiply(inverse(info),score);double largest=0;for(int j=0;j<k;j++){b[j]+=step[j];largest=Math.max(largest,Math.abs(step[j]));}if(largest<1e-8){converged=true;break;}}
        double ll=0,dev=0,pearson=0;for(int i=0;i<n;i++){double eta=b[0];for(int j=1;j<k;j++)eta+=b[j]*x[i][j-1];double mu=Math.exp(Math.max(-30,Math.min(30,eta)));ll+=y[i]*Math.log(mu)-mu-logFactorial(y[i]);dev+=y[i]==0?2*mu:2*(y[i]*Math.log((double)y[i]/mu)-(y[i]-mu));pearson+=sq(y[i]-mu)/mu;}double mean=(double)total/n,nullLL=0;for(int v:y)nullLL+=v*Math.log(mean)-mean-logFactorial(v);double chi=2*(ll-nullLL),pseudo=1-ll/nullLL;double[][]cov=inverse(info);double[]se=new double[k],wald=new double[k],pv=new double[k],irr=new double[k];for(int j=0;j<k;j++){se[j]=Math.sqrt(Math.max(0,cov[j][j]));wald[j]=se[j]>0?sq(b[j]/se[j]):Double.NaN;pv[j]=Double.isFinite(wald[j])?Statistics.chiSquareSurvival(wald[j],1):Double.NaN;irr[j]=Math.exp(Math.min(700,b[j]));}return new Poisson(n,k-1,iterations,converged,ll,dev,pearson,chi,Statistics.chiSquareSurvival(chi,k-1),pseudo,b,se,wald,pv,irr);
    }

    public static Diagnostics regressionDiagnostics(double[][]x,double[]y){
        if(x.length!=y.length||x.length<4)throw new IllegalArgumentException("At least 4 complete observations are required.");int n=x.length,k=x[0].length+1;if(n<=k)throw new IllegalArgumentException("More observations than model parameters are required.");double[][]design=new double[n][k];for(int i=0;i<n;i++){design[i][0]=1;System.arraycopy(x[i],0,design[i],1,k-1);}double[][]xtx=new double[k][k];double[]xty=new double[k];for(int i=0;i<n;i++)for(int a=0;a<k;a++){xty[a]+=design[i][a]*y[i];for(int b=0;b<k;b++)xtx[a][b]+=design[i][a]*design[i][b];}double[][]inv=inverse(xtx);double[]coef=multiply(inv,xty),pred=new double[n],res=new double[n],lev=new double[n],std=new double[n],cook=new double[n];double mean=Arrays.stream(y).average().orElseThrow(),sse=0,sst=0;for(int i=0;i<n;i++){pred[i]=dot(design[i],coef);res[i]=y[i]-pred[i];sse+=res[i]*res[i];sst+=sq(y[i]-mean);lev[i]=quadratic(design[i],inv);}double mse=sse/(n-k);for(int i=0;i<n;i++){std[i]=res[i]/Math.sqrt(Math.max(1e-15,mse*(1-lev[i])));cook[i]=sq(res[i])/(k*mse)*lev[i]/sq(Math.max(1e-12,1-lev[i]));}double r2=1-sse/sst;return new Diagnostics(n,k-1,r2,1-(1-r2)*(n-1)/(n-k),Math.sqrt(mse),coef,pred,res,std,lev,cook);
    }
    private static double fSurvival(double f,int d1,int d2){double x=d2/(d2+d1*f);return regularizedBeta(x,d2/2.0,d1/2.0);}
    private static double regularizedBeta(double x,double a,double b){if(x<=0)return 0;if(x>=1)return 1;double bt=Math.exp(logGamma(a+b)-logGamma(a)-logGamma(b)+a*Math.log(x)+b*Math.log1p(-x));return x<(a+1)/(a+b+2)?bt*betaFraction(x,a,b)/a:1-bt*betaFraction(1-x,b,a)/b;}
    private static double betaFraction(double x,double a,double b){double qab=a+b,qap=a+1,qam=a-1,c=1,d=1-qab*x/qap;if(Math.abs(d)<1e-30)d=1e-30;d=1/d;double h=d;for(int m=1;m<=200;m++){int m2=2*m;double aa=m*(b-m)*x/((qam+m2)*(a+m2));d=1+aa*d;if(Math.abs(d)<1e-30)d=1e-30;c=1+aa/c;if(Math.abs(c)<1e-30)c=1e-30;d=1/d;h*=d*c;aa=-(a+m)*(qab+m)*x/((a+m2)*(qap+m2));d=1+aa*d;if(Math.abs(d)<1e-30)d=1e-30;c=1+aa/c;if(Math.abs(c)<1e-30)c=1e-30;d=1/d;double del=d*c;h*=del;if(Math.abs(del-1)<3e-12)break;}return h;}
    private static double logGamma(double x){double[]c={676.5203681218851,-1259.1392167224028,771.32342877765313,-176.61502916214059,12.507343278686905,-0.13857109526572012,9.9843695780195716e-6,1.5056327351493116e-7};if(x<.5)return Math.log(Math.PI)-Math.log(Math.sin(Math.PI*x))-logGamma(1-x);x-=1;double a=.99999999999980993;for(int i=0;i<c.length;i++)a+=c[i]/(x+i+1);double t=x+c.length-.5;return .5*Math.log(2*Math.PI)+(x+.5)*Math.log(t)-t+Math.log(a);}
    private static double logFactorial(int n){double s=0;for(int i=2;i<=n;i++)s+=Math.log(i);return s;}
    private static double sq(double x){return x*x;}private static double dot(double[]a,double[]b){double s=0;for(int i=0;i<a.length;i++)s+=a[i]*b[i];return s;}private static double quadratic(double[]x,double[][]a){return dot(x,multiply(a,x));}
    private static double[]multiply(double[][]a,double[]b){double[]r=new double[a.length];for(int i=0;i<a.length;i++)for(int j=0;j<b.length;j++)r[i]+=a[i][j]*b[j];return r;}
    private static double[][]inverse(double[][]a){int n=a.length;double[][]m=new double[n][2*n];for(int i=0;i<n;i++){System.arraycopy(a[i],0,m[i],0,n);m[i][n+i]=1;}for(int c=0;c<n;c++){int p=c;for(int r=c+1;r<n;r++)if(Math.abs(m[r][c])>Math.abs(m[p][c]))p=r;if(Math.abs(m[p][c])<1e-12)throw new IllegalArgumentException("Model matrix is singular; remove redundant predictors.");double[]tmp=m[c];m[c]=m[p];m[p]=tmp;double q=m[c][c];for(int j=0;j<2*n;j++)m[c][j]/=q;for(int r=0;r<n;r++)if(r!=c){q=m[r][c];for(int j=0;j<2*n;j++)m[r][j]-=q*m[c][j];}}double[][]inv=new double[n][n];for(int i=0;i<n;i++)System.arraycopy(m[i],n,inv[i],0,n);return inv;}
}
