package com.candyacademia.spsslite;
import java.util.*;
/** Robust inference, resampling and multiple-testing procedures. */
public final class PhaseSevenStatistics {
 private PhaseSevenStatistics(){}
 public record Robust(int n,double median,double mad,double trimmedMean,double winsorizedMean,double q1,double q3,double iqr){}
 public record Normality(int n,double skewness,double excessKurtosis,double jarqueBera,double p){}
 public record VarianceTest(int groups,int df1,int df2,double f,double p){}
 public record WelchAnova(int groups,double df1,double df2,double f,double p){}
 public record Bootstrap(int n,int resamples,double mean,double standardError,double lower,double upper){}
 public record MultipleTest(double[] original,double[] benjaminiHochberg,double[] bonferroni){}
 public static Robust robust(double[]values){double[]x=clean(values);require(x.length>=2,"At least two values are required.");Arrays.sort(x);int trim=(int)Math.floor(.10*x.length);double median=quantile(x,.5),q1=quantile(x,.25),q3=quantile(x,.75);double[]dev=new double[x.length];for(int i=0;i<x.length;i++)dev[i]=Math.abs(x[i]-median);Arrays.sort(dev);double[]w=x.clone();for(int i=0;i<trim;i++){w[i]=x[trim];w[w.length-1-i]=x[x.length-1-trim];}return new Robust(x.length,median,quantile(dev,.5),mean(x,trim,x.length-trim),mean(w,0,w.length),q1,q3,q3-q1);}
 public static Normality jarqueBera(double[]values){double[]x=clean(values);require(x.length>=4,"At least four values are required.");double m=mean(x,0,x.length),m2=0,m3=0,m4=0;for(double v:x){double d=v-m,d2=d*d;m2+=d2;m3+=d2*d;m4+=d2*d2;}m2/=x.length;m3/=x.length;m4/=x.length;require(m2>0,"The variable has no variance.");double skew=m3/Math.pow(m2,1.5),kurt=m4/(m2*m2)-3,jb=x.length/6.0*(skew*skew+kurt*kurt/4);return new Normality(x.length,skew,kurt,jb,Math.exp(-jb/2));}
 public static VarianceTest levene(List<double[]>groups){List<double[]>g=groups.stream().map(PhaseSevenStatistics::clean).filter(a->a.length>1).toList();require(g.size()>=2,"At least two groups with two observations are required.");List<double[]>z=new ArrayList<>();for(double[]a:g){double[]s=a.clone();Arrays.sort(s);double med=quantile(s,.5),d[]=new double[a.length];for(int i=0;i<a.length;i++)d[i]=Math.abs(a[i]-med);z.add(d);}AnovaCore a=anova(z);return new VarianceTest(g.size(),g.size()-1,a.n-g.size(),a.f,1-fCdf(a.f,g.size()-1,a.n-g.size()));}
 public static WelchAnova welchAnova(List<double[]>groups){List<double[]>g=groups.stream().map(PhaseSevenStatistics::clean).filter(a->a.length>1).toList();require(g.size()>=2,"At least two groups with two observations are required.");int k=g.size();double[]w=new double[k],m=new double[k];double sw=0,wm=0;for(int i=0;i<k;i++){m[i]=mean(g.get(i),0,g.get(i).length);double v=variance(g.get(i));require(v>0,"Each group must have non-zero variance.");w[i]=g.get(i).length/v;sw+=w[i];wm+=w[i]*m[i];}wm/=sw;double num=0,c=0;for(int i=0;i<k;i++){num+=w[i]*(m[i]-wm)*(m[i]-wm);double d=1-w[i]/sw;c+=d*d/(g.get(i).length-1.0);}double df1=k-1,df2=(k*k-1)/(3*c),f=(num/df1)/(1+2*(k-2)*c/(k*k-1));return new WelchAnova(k,df1,df2,f,1-fCdf(f,df1,df2));}
 public static Bootstrap bootstrapMean(double[]values,int resamples,double confidence,long seed){double[]x=clean(values);require(x.length>=2,"At least two values are required.");require(resamples>=200&&resamples<=100000,"Resamples must be between 200 and 100000.");require(confidence>.5&&confidence<1,"Confidence must be between 0.50 and 1.00.");Random rng=new Random(seed);double[]b=new double[resamples];for(int r=0;r<resamples;r++){double sum=0;for(int i=0;i<x.length;i++)sum+=x[rng.nextInt(x.length)];b[r]=sum/x.length;}Arrays.sort(b);double avg=mean(b,0,b.length),ss=0;for(double v:b)ss+=(v-avg)*(v-avg);double alpha=(1-confidence)/2;return new Bootstrap(x.length,resamples,mean(x,0,x.length),Math.sqrt(ss/(b.length-1)),quantile(b,alpha),quantile(b,1-alpha));}
 public static MultipleTest adjustPValues(double[]values){double[]p=clean(values);require(p.length>0,"At least one p-value is required.");for(double v:p)require(v>=0&&v<=1,"P-values must be between 0 and 1.");int n=p.length;Integer[]idx=new Integer[n];for(int i=0;i<n;i++)idx[i]=i;Arrays.sort(idx,Comparator.comparingDouble(i->p[i]));double[]bh=new double[n],bon=new double[n];double running=1;for(int rank=n;rank>=1;rank--){int i=idx[rank-1];running=Math.min(running,p[i]*n/rank);bh[i]=Math.min(1,running);}for(int i=0;i<n;i++)bon[i]=Math.min(1,p[i]*n);return new MultipleTest(p,bh,bon);}
 private record AnovaCore(int n,double f){}
 private static AnovaCore anova(List<double[]>g){int n=g.stream().mapToInt(a->a.length).sum();double total=g.stream().flatMapToDouble(Arrays::stream).average().orElseThrow(),between=0,within=0;for(double[]a:g){double m=mean(a,0,a.length);between+=a.length*(m-total)*(m-total);for(double v:a)within+=(v-m)*(v-m);}return new AnovaCore(n,(between/(g.size()-1))/(within/(n-g.size())));}
 private static double[]clean(double[]x){return Arrays.stream(x).filter(Double::isFinite).toArray();}private static double mean(double[]x,int a,int b){double s=0;for(int i=a;i<b;i++)s+=x[i];return s/(b-a);}private static double variance(double[]x){double m=mean(x,0,x.length),s=0;for(double v:x)s+=(v-m)*(v-m);return s/(x.length-1);}private static double quantile(double[]x,double p){double h=(x.length-1)*p;int a=(int)Math.floor(h),b=(int)Math.ceil(h);return x[a]+(h-a)*(x[b]-x[a]);}private static void require(boolean ok,String s){if(!ok)throw new IllegalArgumentException(s);}
 private static double fCdf(double f,double d1,double d2){if(f<=0)return 0;return regularizedBeta(d1*f/(d1*f+d2),d1/2,d2/2);}private static double regularizedBeta(double x,double a,double b){if(x<=0)return 0;if(x>=1)return 1;double bt=Math.exp(logGamma(a+b)-logGamma(a)-logGamma(b)+a*Math.log(x)+b*Math.log1p(-x));return x<(a+1)/(a+b+2)?bt*betaFraction(x,a,b)/a:1-bt*betaFraction(1-x,b,a)/b;}
 private static double betaFraction(double x,double a,double b){double qab=a+b,qap=a+1,qam=a-1,c=1,d=1-qab*x/qap;if(Math.abs(d)<1e-30)d=1e-30;d=1/d;double h=d;for(int m=1;m<=200;m++){int m2=2*m;double aa=m*(b-m)*x/((qam+m2)*(a+m2));d=1+aa*d;if(Math.abs(d)<1e-30)d=1e-30;c=1+aa/c;if(Math.abs(c)<1e-30)c=1e-30;d=1/d;h*=d*c;aa=-(a+m)*(qab+m)*x/((a+m2)*(qap+m2));d=1+aa*d;if(Math.abs(d)<1e-30)d=1e-30;c=1+aa/c;if(Math.abs(c)<1e-30)c=1e-30;d=1/d;double del=d*c;h*=del;if(Math.abs(del-1)<3e-12)break;}return h;}
 private static double logGamma(double x){double[]c={676.5203681218851,-1259.1392167224028,771.32342877765313,-176.61502916214059,12.507343278686905,-.13857109526572012,9.9843695780195716e-6,1.5056327351493116e-7};if(x<.5)return Math.log(Math.PI)-Math.log(Math.sin(Math.PI*x))-logGamma(1-x);x-=1;double a=.99999999999980993;for(int i=0;i<c.length;i++)a+=c[i]/(x+i+1);double t=x+c.length-.5;return .5*Math.log(2*Math.PI)+(x+.5)*Math.log(t)-t+Math.log(a);}
}
