package com.candyacademia.spsslite;
import java.util.*;
public final class PhaseTwoStatistics{
 private PhaseTwoStatistics(){}
 public record Anova(int n,int groups,double ssBetween,double ssWithin,int dfBetween,int dfWithin,double msBetween,double msWithin,double f,double p,double etaSquared){}
 public record RankTest(String name,double statistic,double z,int df,double p,double effectSize){}
 public record MultipleRegression(int n,int predictors,double[] coefficients,double[] standardErrors,double[] t,double[] p,double r2,double adjustedR2,double standardError,double f,double modelP){}
 public static double spearman(double[]x,double[]y){return Statistics.correlation(ranks(x),ranks(y));}
 public static double kendallTauB(double[]x,double[]y){if(x.length!=y.length||x.length<2)return Double.NaN;long con=0,dis=0,tx=0,ty=0;for(int i=0;i<x.length;i++)for(int j=i+1;j<x.length;j++){double dx=Double.compare(x[i],x[j]),dy=Double.compare(y[i],y[j]);if(dx==0&&dy==0)continue;if(dx==0)tx++;else if(dy==0)ty++;else if(dx==dy)con++;else dis++;}return (con-dis)/Math.sqrt((double)(con+dis+tx)*(con+dis+ty));}
 public static Anova anova(Collection<double[]>groups){List<double[]>g=groups.stream().filter(a->a.length>0).toList();if(g.size()<2)throw new IllegalArgumentException("At least 2 non-empty groups are required.");int n=g.stream().mapToInt(a->a.length).sum(),k=g.size();if(n<=k)throw new IllegalArgumentException("Not enough observations within groups.");double grand=g.stream().flatMapToDouble(Arrays::stream).average().orElseThrow(),ssb=0,ssw=0;for(double[]a:g){double m=Arrays.stream(a).average().orElseThrow();ssb+=a.length*(m-grand)*(m-grand);for(double v:a)ssw+=(v-m)*(v-m);}int dfb=k-1,dfw=n-k;double msb=ssb/dfb,msw=ssw/dfw,f=msb/msw;return new Anova(n,k,ssb,ssw,dfb,dfw,msb,msw,f,fSurvival(f,dfb,dfw),ssb/(ssb+ssw));}
 public static RankTest mannWhitney(double[]a,double[]b){if(a.length<1||b.length<1)throw new IllegalArgumentException("Both groups require observations.");double[]all=new double[a.length+b.length];System.arraycopy(a,0,all,0,a.length);System.arraycopy(b,0,all,a.length,b.length);double[]r=ranks(all);double r1=0;for(int i=0;i<a.length;i++)r1+=r[i];double u1=r1-a.length*(a.length+1)/2.0,u2=a.length*b.length-u1,u=Math.min(u1,u2),mean=a.length*b.length/2.0,sd=Math.sqrt(a.length*b.length*(a.length+b.length+1)/12.0),z=(u-mean+0.5)/sd,p=2*(1-normalCdf(Math.abs(z)));return new RankTest("Mann–Whitney U",u,z,0,p,Math.abs(z)/Math.sqrt(a.length+b.length));}
 public static RankTest wilcoxon(double[]a,double[]b){List<Double>d=new ArrayList<>();for(int i=0;i<a.length;i++)if(a[i]!=b[i])d.add(a[i]-b[i]);if(d.size()<2)throw new IllegalArgumentException("At least 2 non-zero paired differences are required.");double[]abs=d.stream().mapToDouble(Math::abs).toArray(),r=ranks(abs);double pos=0,neg=0;for(int i=0;i<r.length;i++)if(d.get(i)>0)pos+=r[i];else neg+=r[i];double w=Math.min(pos,neg),n=d.size(),mean=n*(n+1)/4,sd=Math.sqrt(n*(n+1)*(2*n+1)/24),z=(w-mean+0.5)/sd,p=2*(1-normalCdf(Math.abs(z)));return new RankTest("Wilcoxon signed-rank",w,z,0,p,Math.abs(z)/Math.sqrt(n));}
 public static RankTest kruskalWallis(Collection<double[]>groups){List<double[]>g=groups.stream().filter(a->a.length>0).toList();if(g.size()<2)throw new IllegalArgumentException("At least 2 groups are required.");int n=g.stream().mapToInt(a->a.length).sum(),at=0;double[]all=new double[n];for(double[]a:g){System.arraycopy(a,0,all,at,a.length);at+=a.length;}double[]r=ranks(all);double h=0;at=0;for(double[]a:g){double sum=0;for(int i=0;i<a.length;i++)sum+=r[at++];h+=sum*sum/a.length;}h=12*h/(n*(n+1.0))-3*(n+1);int df=g.size()-1;return new RankTest("Kruskal–Wallis H",h,Double.NaN,df,Statistics.chiSquareSurvival(h,df),h/(n-1));}
 public static MultipleRegression multipleRegression(double[][]x,double[]y){int n=y.length,p=x[0].length,k=p+1;if(n<=k)throw new IllegalArgumentException("More complete observations than model parameters are required.");double[][]design=new double[n][k];for(int i=0;i<n;i++){design[i][0]=1;System.arraycopy(x[i],0,design[i],1,p);}double[][]xtx=new double[k][k];double[]xty=new double[k];for(int i=0;i<n;i++)for(int a=0;a<k;a++){xty[a]+=design[i][a]*y[i];for(int b=0;b<k;b++)xtx[a][b]+=design[i][a]*design[i][b];}double[][]inv=invert(xtx);double[]beta=matVec(inv,xty);double mean=Arrays.stream(y).average().orElseThrow(),sse=0,sst=0;for(int i=0;i<n;i++){double fit=0;for(int j=0;j<k;j++)fit+=design[i][j]*beta[j];sse+=(y[i]-fit)*(y[i]-fit);sst+=(y[i]-mean)*(y[i]-mean);}double mse=sse/(n-k),seModel=Math.sqrt(mse),r2=1-sse/sst,adj=1-(1-r2)*(n-1)/(n-k),f=(r2/p)/((1-r2)/(n-k));double[]se=new double[k],t=new double[k],pv=new double[k];for(int j=0;j<k;j++){se[j]=Math.sqrt(mse*inv[j][j]);t[j]=beta[j]/se[j];pv[j]=Statistics.twoTailedTP(t[j],n-k);}return new MultipleRegression(n,p,beta,se,t,pv,r2,adj,seModel,f,fSurvival(f,p,n-k));}
 private static double[]ranks(double[]a){Integer[]idx=new Integer[a.length];for(int i=0;i<a.length;i++)idx[i]=i;Arrays.sort(idx,Comparator.comparingDouble(i->a[i]));double[]r=new double[a.length];int i=0;while(i<a.length){int j=i+1;while(j<a.length&&Double.compare(a[idx[i]],a[idx[j]])==0)j++;double rank=(i+j+1)/2.0;for(int z=i;z<j;z++)r[idx[z]]=rank;i=j;}return r;}
 private static double[][]invert(double[][]a){int n=a.length;double[][]m=new double[n][2*n];for(int i=0;i<n;i++){System.arraycopy(a[i],0,m[i],0,n);m[i][n+i]=1;}for(int c=0;c<n;c++){int pivot=c;for(int r=c+1;r<n;r++)if(Math.abs(m[r][c])>Math.abs(m[pivot][c]))pivot=r;if(Math.abs(m[pivot][c])<1e-12)throw new IllegalArgumentException("Predictors are linearly dependent.");double[]tmp=m[c];m[c]=m[pivot];m[pivot]=tmp;double d=m[c][c];for(int j=0;j<2*n;j++)m[c][j]/=d;for(int r=0;r<n;r++)if(r!=c){double q=m[r][c];for(int j=0;j<2*n;j++)m[r][j]-=q*m[c][j];}}double[][]out=new double[n][n];for(int i=0;i<n;i++)System.arraycopy(m[i],n,out[i],0,n);return out;}
 private static double[]matVec(double[][]a,double[]x){double[]y=new double[a.length];for(int i=0;i<a.length;i++)for(int j=0;j<x.length;j++)y[i]+=a[i][j]*x[j];return y;}
 private static double normalCdf(double x){double t=1/(1+0.2316419*Math.abs(x)),d=0.3989422804014327*Math.exp(-x*x/2),p=1-d*t*(0.319381530+t*(-0.356563782+t*(1.781477937+t*(-1.821255978+t*1.330274429))));return x>=0?p:1-p;}
 private static double fSurvival(double f,double d1,double d2){return regularizedBeta(d2/(d2+d1*f),d2/2,d1/2);}
 private static double regularizedBeta(double x,double a,double b){if(x<=0)return 0;if(x>=1)return 1;double bt=Math.exp(logGamma(a+b)-logGamma(a)-logGamma(b)+a*Math.log(x)+b*Math.log1p(-x));return x<(a+1)/(a+b+2)?bt*betaFraction(x,a,b)/a:1-bt*betaFraction(1-x,b,a)/b;}
 private static double betaFraction(double x,double a,double b){double qab=a+b,qap=a+1,qam=a-1,c=1,d=1-qab*x/qap;if(Math.abs(d)<1e-30)d=1e-30;d=1/d;double h=d;for(int m=1;m<=200;m++){int m2=2*m;double aa=m*(b-m)*x/((qam+m2)*(a+m2));d=1+aa*d;if(Math.abs(d)<1e-30)d=1e-30;c=1+aa/c;if(Math.abs(c)<1e-30)c=1e-30;d=1/d;h*=d*c;aa=-(a+m)*(qab+m)*x/((a+m2)*(qap+m2));d=1+aa*d;if(Math.abs(d)<1e-30)d=1e-30;c=1+aa/c;if(Math.abs(c)<1e-30)c=1e-30;d=1/d;double del=d*c;h*=del;if(Math.abs(del-1)<3e-12)break;}return h;}
 private static double logGamma(double x){double[]c={676.5203681218851,-1259.1392167224028,771.32342877765313,-176.61502916214059,12.507343278686905,-0.13857109526572012,9.9843695780195716e-6,1.5056327351493116e-7};if(x<.5)return Math.log(Math.PI)-Math.log(Math.sin(Math.PI*x))-logGamma(1-x);x--;double a=.99999999999980993;for(int i=0;i<c.length;i++)a+=c[i]/(x+i+1);double t=x+c.length-.5;return .5*Math.log(2*Math.PI)+(x+.5)*Math.log(t)-t+Math.log(a);}
}
