package com.candyacademia.spsslite;
import java.util.*;
public final class PhaseOneStatistics {
 private PhaseOneStatistics(){}
 public record Explore(int n,int missing,double mean,double se,double ciLow,double ciHigh,double variance,double sd,double median,double q1,double q3,double min,double max,double range,double iqr,double skewness,double excessKurtosis,double jarqueBera,double normalityP){}
 public record OneSample(int n,double mean,double testValue,double difference,double se,double t,double df,double p,double ciLow,double ciHigh,double cohenD){}
 public record Paired(int n,double mean1,double mean2,double meanDifference,double sdDifference,double t,double df,double p,double ciLow,double ciHigh,double cohenDz){}
 public record Frequency(String value,int count,double percent,double validPercent,double cumulativePercent){}
 public static Explore explore(List<Double> values,int total){double[]a=values.stream().filter(Objects::nonNull).mapToDouble(Double::doubleValue).sorted().toArray();if(a.length==0)return new Explore(0,total,Double.NaN,Double.NaN,Double.NaN,Double.NaN,Double.NaN,Double.NaN,Double.NaN,Double.NaN,Double.NaN,Double.NaN,Double.NaN,Double.NaN,Double.NaN,Double.NaN,Double.NaN,Double.NaN,Double.NaN);int n=a.length;double mean=Arrays.stream(a).average().orElseThrow(),ss=0,m3=0,m4=0;for(double v:a){double d=v-mean,d2=d*d;ss+=d2;m3+=d2*d;m4+=d2*d2;}double variance=n>1?ss/(n-1):0,sd=Math.sqrt(variance),se=sd/Math.sqrt(n),crit=n>1?tCritical95(n-1):Double.NaN;double skew=n>2?(n*m3)/((n-1.0)*(n-2)*Math.pow(sd,3)):Double.NaN;double kurt=n>3?(n*(n+1)*m4/((n-1.0)*(n-2)*(n-3)*Math.pow(sd,4)))-(3.0*(n-1)*(n-1)/((n-2.0)*(n-3))):Double.NaN;double jb=n>3?n/6.0*(skew*skew+kurt*kurt/4):Double.NaN;return new Explore(n,total-n,mean,se,mean-crit*se,mean+crit*se,variance,sd,percentile(a,.5),percentile(a,.25),percentile(a,.75),a[0],a[n-1],a[n-1]-a[0],percentile(a,.75)-percentile(a,.25),skew,kurt,jb,Double.isNaN(jb)?Double.NaN:Math.exp(-jb/2));}
 public static OneSample oneSample(double[]a,double mu){if(a.length<2)throw new IllegalArgumentException("At least 2 observations are required.");double mean=Arrays.stream(a).average().orElseThrow(),sd=sd(a,mean),se=sd/Math.sqrt(a.length),t=(mean-mu)/se,df=a.length-1,crit=tCritical95(df);return new OneSample(a.length,mean,mu,mean-mu,se,t,df,Statistics.twoTailedTP(t,df),mean-mu-crit*se,mean-mu+crit*se,(mean-mu)/sd);}
 public static Paired paired(double[]a,double[]b){if(a.length!=b.length||a.length<2)throw new IllegalArgumentException("At least 2 paired observations are required.");double[]d=new double[a.length];for(int i=0;i<a.length;i++)d[i]=a[i]-b[i];double m1=Arrays.stream(a).average().orElseThrow(),m2=Arrays.stream(b).average().orElseThrow(),md=Arrays.stream(d).average().orElseThrow(),sd=sd(d,md),se=sd/Math.sqrt(d.length),t=md/se,df=d.length-1,crit=tCritical95(df);return new Paired(d.length,m1,m2,md,sd,t,df,Statistics.twoTailedTP(t,df),md-crit*se,md+crit*se,md/sd);}
 public static List<Frequency> frequencies(List<String> raw,int total){Map<String,Integer>map=new TreeMap<>();for(String s:raw)if(s!=null&&!s.isBlank())map.merge(s,1,Integer::sum);int valid=map.values().stream().mapToInt(Integer::intValue).sum(),cum=0;List<Frequency>out=new ArrayList<>();for(var e:map.entrySet()){cum+=e.getValue();out.add(new Frequency(e.getKey(),e.getValue(),total==0?0:100.0*e.getValue()/total,valid==0?0:100.0*e.getValue()/valid,valid==0?0:100.0*cum/valid));}return out;}
 public static String missingSummary(javax.swing.table.DefaultTableModel m){StringBuilder s=new StringBuilder("MISSING-DATA SUMMARY\nVariable\tValid\tMissing\tMissing %\n");for(int c=0;c<m.getColumnCount();c++){int valid=0;for(int r=0;r<m.getRowCount();r++)if(!DataSet.text(m,r,c).isBlank())valid++;int missing=m.getRowCount()-valid;s.append(String.format("%s\t%d\t%d\t%.2f%%\n",m.getColumnName(c),valid,missing,m.getRowCount()==0?0:100.0*missing/m.getRowCount()));}return s.toString();}
 public static int appendZScores(javax.swing.table.DefaultTableModel m,int col){List<Double>v=DataSet.numeric(m,col);if(v.size()<2)throw new IllegalArgumentException("At least 2 numeric values are required.");double mean=v.stream().mapToDouble(Double::doubleValue).average().orElseThrow(),sd=Math.sqrt(v.stream().mapToDouble(x->(x-mean)*(x-mean)).sum()/(v.size()-1));int newCol=m.getColumnCount();m.addColumn("Z_"+m.getColumnName(col));for(int r=0;r<m.getRowCount();r++)try{String x=DataSet.text(m,r,col);m.setValueAt(x.isBlank()?"":String.format(Locale.ROOT,"%.6f",(Double.parseDouble(x)-mean)/sd),r,newCol);}catch(NumberFormatException e){m.setValueAt("",r,newCol);}return newCol;}
 private static double sd(double[]a,double m){double s=0;for(double v:a)s+=(v-m)*(v-m);return Math.sqrt(s/(a.length-1));}
 private static double percentile(double[]a,double p){if(a.length==1)return a[0];double pos=p*(a.length-1),lo=Math.floor(pos),hi=Math.ceil(pos);return a[(int)lo]+(pos-lo)*(a[(int)hi]-a[(int)lo]);}
 private static double tCritical95(double df){if(df<=1)return 12.706;if(df==2)return 4.303;if(df==3)return 3.182;if(df==4)return 2.776;if(df==5)return 2.571;if(df<=7)return 2.447;if(df<=10)return 2.306;if(df<=15)return 2.131;if(df<=20)return 2.086;if(df<=30)return 2.042;if(df<=40)return 2.021;if(df<=60)return 2.000;if(df<=120)return 1.980;return 1.960;}
}
