package com.candyacademia.spsslite;
import java.util.*;
public final class PhaseThreeStatistics{
 private PhaseThreeStatistics(){}
 public record Reliability(int n,int items,double alpha,double[] correctedItemTotal,double[] alphaIfDeleted){}
 public record PCA(int n,int variables,double[] eigenvalues,double[] explainedPercent,double[] cumulativePercent,double[][] loadings){}
 public record Factor(int n,int variables,int factors,double[][] unrotated,double[][] rotated,double[] communalities){}
 public record KMeans(int n,int variables,int clusters,int iterations,double[][] centroids,int[] assignments,int[] sizes,double withinClusterSS){}
 public static Reliability reliability(double[][]x){check(x,2);int n=x.length,k=x[0].length;if(k<2)throw new IllegalArgumentException("Select at least 2 scale items.");double totalVar=variance(rowSums(x)),sumVar=0;for(int j=0;j<k;j++)sumVar+=variance(column(x,j));double alpha=k/(k-1.0)*(1-sumVar/totalVar);double[]citc=new double[k],aid=new double[k];for(int j=0;j<k;j++){double[]item=column(x,j),rest=new double[n];for(int i=0;i<n;i++){for(int q=0;q<k;q++)if(q!=j)rest[i]+=x[i][q];}citc[j]=Statistics.correlation(item,rest);if(k==2)aid[j]=Double.NaN;else{double sv=0;for(int q=0;q<k;q++)if(q!=j)sv+=variance(column(x,q));aid[j]=(k-1.0)/(k-2)*(1-sv/variance(rest));}}return new Reliability(n,k,alpha,citc,aid);}
 public static PCA pca(double[][]x){check(x,2);double[][]z=standardize(x),corr=cross(z),v=identity(x[0].length);double[]eval=jacobi(corr,v);sortEigen(eval,v);double[]pct=new double[eval.length],cum=new double[eval.length];double[][]load=new double[eval.length][eval.length];double running=0;for(int j=0;j<eval.length;j++){pct[j]=100*Math.max(0,eval[j])/eval.length;running+=pct[j];cum[j]=running;for(int i=0;i<eval.length;i++)load[i][j]=v[i][j]*Math.sqrt(Math.max(0,eval[j]));}return new PCA(x.length,x[0].length,eval,pct,cum,load);}
 public static Factor factor(double[][]x,int factors){PCA p=pca(x);if(factors<1||factors>p.variables())throw new IllegalArgumentException("Invalid factor count.");double[][]u=new double[p.variables()][factors];for(int i=0;i<u.length;i++)System.arraycopy(p.loadings()[i],0,u[i],0,factors);double[][]r=varimax(u),com=new double[p.variables()][1];double[]comm=new double[p.variables()];for(int i=0;i<r.length;i++)for(int j=0;j<factors;j++)comm[i]+=r[i][j]*r[i][j];return new Factor(p.n(),p.variables(),factors,u,r,comm);}
 public static KMeans kmeans(double[][]raw,int k,int maxIterations){check(raw,2);if(k<2||k>=raw.length)throw new IllegalArgumentException("Clusters must be at least 2 and fewer than observations.");double[][]x=standardize(raw),cent=new double[k][x[0].length];for(int c=0;c<k;c++)cent[c]=x[(int)((long)c*(x.length-1)/(k-1))].clone();int[]a=new int[x.length];Arrays.fill(a,-1);int iter=0;for(;iter<maxIterations;iter++){boolean changed=false;for(int i=0;i<x.length;i++){int best=0;double bd=dist(x[i],cent[0]);for(int c=1;c<k;c++){double d=dist(x[i],cent[c]);if(d<bd){bd=d;best=c;}}if(a[i]!=best){a[i]=best;changed=true;}}double[][]next=new double[k][x[0].length];int[]size=new int[k];for(int i=0;i<x.length;i++){size[a[i]]++;for(int j=0;j<x[i].length;j++)next[a[i]][j]+=x[i][j];}for(int c=0;c<k;c++){if(size[c]==0)next[c]=cent[c].clone();else for(int j=0;j<next[c].length;j++)next[c][j]/=size[c];}cent=next;if(!changed){iter++;break;}}int[]sizes=new int[k];double w=0;for(int i=0;i<x.length;i++){sizes[a[i]]++;w+=dist(x[i],cent[a[i]]);}return new KMeans(x.length,x[0].length,k,iter,cent,a,sizes,w);}
 private static void check(double[][]x,int min){if(x==null||x.length<min||x[0].length<1)throw new IllegalArgumentException("Not enough complete numeric observations.");for(double[]r:x)if(r.length!=x[0].length)throw new IllegalArgumentException("Ragged data matrix.");}
 private static double[]rowSums(double[][]x){double[]s=new double[x.length];for(int i=0;i<x.length;i++)for(double v:x[i])s[i]+=v;return s;}
 private static double[]column(double[][]x,int c){double[]v=new double[x.length];for(int i=0;i<x.length;i++)v[i]=x[i][c];return v;}
 private static double variance(double[]x){double m=Arrays.stream(x).average().orElseThrow(),s=0;for(double v:x)s+=(v-m)*(v-m);return s/(x.length-1);}
 private static double[][]standardize(double[][]x){int n=x.length,p=x[0].length;double[][]z=new double[n][p];for(int j=0;j<p;j++){double[]c=column(x,j);double m=Arrays.stream(c).average().orElseThrow(),sd=Math.sqrt(variance(c));if(sd==0)throw new IllegalArgumentException("A selected variable has zero variance.");for(int i=0;i<n;i++)z[i][j]=(x[i][j]-m)/sd;}return z;}
 private static double[][]cross(double[][]z){int n=z.length,p=z[0].length;double[][]c=new double[p][p];for(int i=0;i<p;i++)for(int j=0;j<p;j++){for(int r=0;r<n;r++)c[i][j]+=z[r][i]*z[r][j];c[i][j]/=n-1;}return c;}
 private static double[][]identity(int n){double[][]a=new double[n][n];for(int i=0;i<n;i++)a[i][i]=1;return a;}
 private static double[]jacobi(double[][]a,double[][]v){int n=a.length;for(int it=0;it<100*n*n;it++){int p=0,q=1;double max=0;for(int i=0;i<n;i++)for(int j=i+1;j<n;j++)if(Math.abs(a[i][j])>max){max=Math.abs(a[i][j]);p=i;q=j;}if(max<1e-12)break;double phi=.5*Math.atan2(2*a[p][q],a[q][q]-a[p][p]),c=Math.cos(phi),s=Math.sin(phi),app=a[p][p],aqq=a[q][q],apq=a[p][q];a[p][p]=c*c*app-2*s*c*apq+s*s*aqq;a[q][q]=s*s*app+2*s*c*apq+c*c*aqq;a[p][q]=a[q][p]=0;for(int i=0;i<n;i++)if(i!=p&&i!=q){double aip=a[i][p],aiq=a[i][q];a[i][p]=a[p][i]=c*aip-s*aiq;a[i][q]=a[q][i]=s*aip+c*aiq;}for(int i=0;i<n;i++){double vip=v[i][p],viq=v[i][q];v[i][p]=c*vip-s*viq;v[i][q]=s*vip+c*viq;}}double[]e=new double[n];for(int i=0;i<n;i++)e[i]=a[i][i];return e;}
 private static void sortEigen(double[]e,double[][]v){for(int i=0;i<e.length-1;i++){int b=i;for(int j=i+1;j<e.length;j++)if(e[j]>e[b])b=j;if(b!=i){double t=e[i];e[i]=e[b];e[b]=t;for(int r=0;r<v.length;r++){t=v[r][i];v[r][i]=v[r][b];v[r][b]=t;}}}}
 private static double[][]varimax(double[][]l){int p=l.length,k=l[0].length;double[][]r=new double[p][k];for(int i=0;i<p;i++)r[i]=l[i].clone();for(int iter=0;iter<100;iter++){double change=0;for(int a=0;a<k-1;a++)for(int b=a+1;b<k;b++){double u=0,v=0;for(int i=0;i<p;i++){double x=r[i][a],y=r[i][b];u+=2*x*y*(x*x-y*y);v+=(x*x-y*y)*(x*x-y*y)-4*x*x*y*y;}double angle=.25*Math.atan2(u,v);change=Math.max(change,Math.abs(angle));double c=Math.cos(angle),s=Math.sin(angle);for(int i=0;i<p;i++){double x=r[i][a],y=r[i][b];r[i][a]=c*x+s*y;r[i][b]=-s*x+c*y;}}if(change<1e-7)break;}return r;}
 private static double dist(double[]a,double[]b){double s=0;for(int i=0;i<a.length;i++){double d=a[i]-b[i];s+=d*d;}return s;}
}
